window.__LANGUAGE_LEARNING_BUNDLE__ = {
  "meta": {
    "schema_version": "2.0",
    "generated_at": "2026-07-23T12:42:13.608880+00:00",
    "input_file": "content/monika-address-work-qa.txt",
    "study_column": 0,
    "reference_column": 1,
    "mode": "both",
    "voice": "pl-PL-ZofiaNeural",
    "study_language_name": "Polish",
    "reference_language_name": "English",
    "dashboard_title": "Monika Address & Work Practice",
    "dashboard_subtitle": "Practice address, housing, work, vocabulary, conjugation, and motivation with Polish audio.",
    "output_dir_name": "output-monika-pack",
    "profile_file": null,
    "pronunciation_file": null,
    "entry_count": 21,
    "item_count": 42
  },
  "items": [
    {
      "ordinal": 1,
      "entry_index": 1,
      "kind": "question",
      "display_text": "Z kim pan/pani mieszka teraz?",
      "translation_text": "Who do you live with now?",
      "spoken_text": "Z kim pan/pani mieszka teraz?",
      "text": "Z kim pan/pani mieszka teraz?",
      "original_text": "Z kim pan/pani mieszka teraz?",
      "original_reference_text": "Who do you live with now?",
      "display_question": "Q: Z kim pan/pani mieszka teraz?",
      "display_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "reference_question": "Q: Who do you live with now?",
      "reference_answer": "A: I live with my family, that is my husband and my daughter.",
      "source_question": "Q: Z kim pan/pani mieszka teraz?",
      "source_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "output_file": "audio/0001-entry-0001-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0001-entry-0001-question.mp3"
    },
    {
      "ordinal": 2,
      "entry_index": 1,
      "kind": "answer",
      "display_text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "translation_text": "I live with my family, that is my husband and my daughter.",
      "spoken_text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "original_text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "original_reference_text": "I live with my family, that is my husband and my daughter.",
      "display_question": "Q: Z kim pan/pani mieszka teraz?",
      "display_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "reference_question": "Q: Who do you live with now?",
      "reference_answer": "A: I live with my family, that is my husband and my daughter.",
      "source_question": "Q: Z kim pan/pani mieszka teraz?",
      "source_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
      "output_file": "audio/0002-entry-0001-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0002-entry-0001-answer.mp3"
    },
    {
      "ordinal": 3,
      "entry_index": 2,
      "kind": "question",
      "display_text": "Na jakim stanowisku pan/pani pracuje w firmie?",
      "translation_text": "What position do you work in at your company?",
      "spoken_text": "Na jakim stanowisku pan/pani pracuje w firmie?",
      "text": "Na jakim stanowisku pan/pani pracuje w firmie?",
      "original_text": "Na jakim stanowisku pan/pani pracuje w firmie?",
      "original_reference_text": "What position do you work in at your company?",
      "display_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
      "display_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
      "reference_question": "Q: What position do you work in at your company?",
      "reference_answer": "A: I work as a deputy director.",
      "source_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
      "source_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
      "output_file": "audio/0003-entry-0002-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0003-entry-0002-question.mp3"
    },
    {
      "ordinal": 4,
      "entry_index": 2,
      "kind": "answer",
      "display_text": "Pracuję na stanowisku zastępcy dyrektora.",
      "translation_text": "I work as a deputy director.",
      "spoken_text": "Pracuję na stanowisku zastępcy dyrektora.",
      "text": "Pracuję na stanowisku zastępcy dyrektora.",
      "original_text": "Pracuję na stanowisku zastępcy dyrektora.",
      "original_reference_text": "I work as a deputy director.",
      "display_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
      "display_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
      "reference_question": "Q: What position do you work in at your company?",
      "reference_answer": "A: I work as a deputy director.",
      "source_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
      "source_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
      "output_file": "audio/0004-entry-0002-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0004-entry-0002-answer.mp3"
    },
    {
      "ordinal": 5,
      "entry_index": 3,
      "kind": "question",
      "display_text": "Gdzie pani pracuje, w domu online czy w biurze?",
      "translation_text": "Where do you work, from home online or in the office?",
      "spoken_text": "Gdzie pani pracuje, w domu online czy w biurze?",
      "text": "Gdzie pani pracuje, w domu online czy w biurze?",
      "original_text": "Gdzie pani pracuje, w domu online czy w biurze?",
      "original_reference_text": "Where do you work, from home online or in the office?",
      "display_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
      "display_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "reference_question": "Q: Where do you work, from home online or in the office?",
      "reference_answer": "A: I work from home two days a week and in the office three days a week.",
      "source_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
      "source_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "output_file": "audio/0005-entry-0003-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0005-entry-0003-question.mp3"
    },
    {
      "ordinal": 6,
      "entry_index": 3,
      "kind": "answer",
      "display_text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "translation_text": "I work from home two days a week and in the office three days a week.",
      "spoken_text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "original_text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "original_reference_text": "I work from home two days a week and in the office three days a week.",
      "display_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
      "display_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "reference_question": "Q: Where do you work, from home online or in the office?",
      "reference_answer": "A: I work from home two days a week and in the office three days a week.",
      "source_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
      "source_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
      "output_file": "audio/0006-entry-0003-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0006-entry-0003-answer.mp3"
    },
    {
      "ordinal": 7,
      "entry_index": 4,
      "kind": "question",
      "display_text": "Pod jakim adresem mieszkasz?",
      "translation_text": "What address do you live at?",
      "spoken_text": "Pod jakim adresem mieszkasz?",
      "text": "Pod jakim adresem mieszkasz?",
      "original_text": "Pod jakim adresem mieszkasz?",
      "original_reference_text": "What address do you live at?",
      "display_question": "Q: Pod jakim adresem mieszkasz?",
      "display_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "reference_question": "Q: What address do you live at?",
      "reference_answer": "A: I currently live in Krakow at osiedle Piastów 56C/120.",
      "source_question": "Q: Pod jakim adresem mieszkasz?",
      "source_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "output_file": "audio/0007-entry-0004-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0007-entry-0004-question.mp3"
    },
    {
      "ordinal": 8,
      "entry_index": 4,
      "kind": "answer",
      "display_text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "translation_text": "I currently live in Krakow at osiedle Piastów 56C/120.",
      "spoken_text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "original_text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "original_reference_text": "I currently live in Krakow at osiedle Piastów 56C/120.",
      "display_question": "Q: Pod jakim adresem mieszkasz?",
      "display_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "reference_question": "Q: What address do you live at?",
      "reference_answer": "A: I currently live in Krakow at osiedle Piastów 56C/120.",
      "source_question": "Q: Pod jakim adresem mieszkasz?",
      "source_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "output_file": "audio/0008-entry-0004-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0008-entry-0004-answer.mp3"
    },
    {
      "ordinal": 9,
      "entry_index": 5,
      "kind": "question",
      "display_text": "Gdzie mieszkasz?",
      "translation_text": "Where do you live?",
      "spoken_text": "Gdzie mieszkasz?",
      "text": "Gdzie mieszkasz?",
      "original_text": "Gdzie mieszkasz?",
      "original_reference_text": "Where do you live?",
      "display_question": "Q: Gdzie mieszkasz?",
      "display_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "reference_question": "Q: Where do you live?",
      "reference_answer": "A: I live in Krakow at osiedle Piastów 56C/120.",
      "source_question": "Q: Gdzie mieszkasz?",
      "source_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "output_file": "audio/0009-entry-0005-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0009-entry-0005-question.mp3"
    },
    {
      "ordinal": 10,
      "entry_index": 5,
      "kind": "answer",
      "display_text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "translation_text": "I live in Krakow at osiedle Piastów 56C/120.",
      "spoken_text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "original_text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "original_reference_text": "I live in Krakow at osiedle Piastów 56C/120.",
      "display_question": "Q: Gdzie mieszkasz?",
      "display_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "reference_question": "Q: Where do you live?",
      "reference_answer": "A: I live in Krakow at osiedle Piastów 56C/120.",
      "source_question": "Q: Gdzie mieszkasz?",
      "source_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
      "output_file": "audio/0010-entry-0005-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0010-entry-0005-answer.mp3"
    },
    {
      "ordinal": 11,
      "entry_index": 6,
      "kind": "question",
      "display_text": "Jaki jest twój obecny adres?",
      "translation_text": "What is your current address?",
      "spoken_text": "Jaki jest twój obecny adres?",
      "text": "Jaki jest twój obecny adres?",
      "original_text": "Jaki jest twój obecny adres?",
      "original_reference_text": "What is your current address?",
      "display_question": "Q: Jaki jest twój obecny adres?",
      "display_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
      "reference_question": "Q: What is your current address?",
      "reference_answer": "A: My current address is: osiedle Piastów 56C/120.",
      "source_question": "Q: Jaki jest twój obecny adres?",
      "source_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
      "output_file": "audio/0011-entry-0006-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0011-entry-0006-question.mp3"
    },
    {
      "ordinal": 12,
      "entry_index": 6,
      "kind": "answer",
      "display_text": "Mój obecny adres to: osiedle Piastów 56C/120.",
      "translation_text": "My current address is: osiedle Piastów 56C/120.",
      "spoken_text": "Mój obecny adres to: osiedle Piastów 56C/120.",
      "text": "Mój obecny adres to: osiedle Piastów 56C/120.",
      "original_text": "Mój obecny adres to: osiedle Piastów 56C/120.",
      "original_reference_text": "My current address is: osiedle Piastów 56C/120.",
      "display_question": "Q: Jaki jest twój obecny adres?",
      "display_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
      "reference_question": "Q: What is your current address?",
      "reference_answer": "A: My current address is: osiedle Piastów 56C/120.",
      "source_question": "Q: Jaki jest twój obecny adres?",
      "source_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
      "output_file": "audio/0012-entry-0006-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0012-entry-0006-answer.mp3"
    },
    {
      "ordinal": 13,
      "entry_index": 7,
      "kind": "question",
      "display_text": "Czy mieszkasz w wynajętym mieszkaniu?",
      "translation_text": "Are you staying in a rental property?",
      "spoken_text": "Czy mieszkasz w wynajętym mieszkaniu?",
      "text": "Czy mieszkasz w wynajętym mieszkaniu?",
      "original_text": "Czy mieszkasz w wynajętym mieszkaniu?",
      "original_reference_text": "Are you staying in a rental property?",
      "display_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
      "display_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "reference_question": "Q: Are you staying in a rental property?",
      "reference_answer": "A: No, I do not rent. This is my own apartment.",
      "source_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
      "source_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "output_file": "audio/0013-entry-0007-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0013-entry-0007-question.mp3"
    },
    {
      "ordinal": 14,
      "entry_index": 7,
      "kind": "answer",
      "display_text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "translation_text": "No, I do not rent. This is my own apartment.",
      "spoken_text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "original_text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "original_reference_text": "No, I do not rent. This is my own apartment.",
      "display_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
      "display_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "reference_question": "Q: Are you staying in a rental property?",
      "reference_answer": "A: No, I do not rent. This is my own apartment.",
      "source_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
      "source_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
      "output_file": "audio/0014-entry-0007-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0014-entry-0007-answer.mp3"
    },
    {
      "ordinal": 15,
      "entry_index": 8,
      "kind": "question",
      "display_text": "Czy wynajmujesz mieszkanie?",
      "translation_text": "Do you rent an apartment?",
      "spoken_text": "Czy wynajmujesz mieszkanie?",
      "text": "Czy wynajmujesz mieszkanie?",
      "original_text": "Czy wynajmujesz mieszkanie?",
      "original_reference_text": "Do you rent an apartment?",
      "display_question": "Q: Czy wynajmujesz mieszkanie?",
      "display_answer": "A: Tak, wynajmuję mieszkanie.",
      "reference_question": "Q: Do you rent an apartment?",
      "reference_answer": "A: Yes, I rent an apartment.",
      "source_question": "Q: Czy wynajmujesz mieszkanie?",
      "source_answer": "A: Tak, wynajmuję mieszkanie.",
      "output_file": "audio/0015-entry-0008-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0015-entry-0008-question.mp3"
    },
    {
      "ordinal": 16,
      "entry_index": 8,
      "kind": "answer",
      "display_text": "Tak, wynajmuję mieszkanie.",
      "translation_text": "Yes, I rent an apartment.",
      "spoken_text": "Tak, wynajmuję mieszkanie.",
      "text": "Tak, wynajmuję mieszkanie.",
      "original_text": "Tak, wynajmuję mieszkanie.",
      "original_reference_text": "Yes, I rent an apartment.",
      "display_question": "Q: Czy wynajmujesz mieszkanie?",
      "display_answer": "A: Tak, wynajmuję mieszkanie.",
      "reference_question": "Q: Do you rent an apartment?",
      "reference_answer": "A: Yes, I rent an apartment.",
      "source_question": "Q: Czy wynajmujesz mieszkanie?",
      "source_answer": "A: Tak, wynajmuję mieszkanie.",
      "output_file": "audio/0016-entry-0008-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0016-entry-0008-answer.mp3"
    },
    {
      "ordinal": 17,
      "entry_index": 9,
      "kind": "question",
      "display_text": "Czy posiadasz własną nieruchomość?",
      "translation_text": "Do you own a property?",
      "spoken_text": "Czy posiadasz własną nieruchomość?",
      "text": "Czy posiadasz własną nieruchomość?",
      "original_text": "Czy posiadasz własną nieruchomość?",
      "original_reference_text": "Do you own a property?",
      "display_question": "Q: Czy posiadasz własną nieruchomość?",
      "display_answer": "A: Tak, mam własną nieruchomość.",
      "reference_question": "Q: Do you own a property?",
      "reference_answer": "A: Yes, I own a property.",
      "source_question": "Q: Czy posiadasz własną nieruchomość?",
      "source_answer": "A: Tak, mam własną nieruchomość.",
      "output_file": "audio/0017-entry-0009-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0017-entry-0009-question.mp3"
    },
    {
      "ordinal": 18,
      "entry_index": 9,
      "kind": "answer",
      "display_text": "Tak, mam własną nieruchomość.",
      "translation_text": "Yes, I own a property.",
      "spoken_text": "Tak, mam własną nieruchomość.",
      "text": "Tak, mam własną nieruchomość.",
      "original_text": "Tak, mam własną nieruchomość.",
      "original_reference_text": "Yes, I own a property.",
      "display_question": "Q: Czy posiadasz własną nieruchomość?",
      "display_answer": "A: Tak, mam własną nieruchomość.",
      "reference_question": "Q: Do you own a property?",
      "reference_answer": "A: Yes, I own a property.",
      "source_question": "Q: Czy posiadasz własną nieruchomość?",
      "source_answer": "A: Tak, mam własną nieruchomość.",
      "output_file": "audio/0018-entry-0009-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0018-entry-0009-answer.mp3"
    },
    {
      "ordinal": 19,
      "entry_index": 10,
      "kind": "question",
      "display_text": "Czy mieszkasz sam/sama?",
      "translation_text": "Do you live alone?",
      "spoken_text": "Czy mieszkasz sam/sama?",
      "text": "Czy mieszkasz sam/sama?",
      "original_text": "Czy mieszkasz sam/sama?",
      "original_reference_text": "Do you live alone?",
      "display_question": "Q: Czy mieszkasz sam/sama?",
      "display_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "reference_question": "Q: Do you live alone?",
      "reference_answer": "A: No, I do not live alone. I live with my family.",
      "source_question": "Q: Czy mieszkasz sam/sama?",
      "source_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "output_file": "audio/0019-entry-0010-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0019-entry-0010-question.mp3"
    },
    {
      "ordinal": 20,
      "entry_index": 10,
      "kind": "answer",
      "display_text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "translation_text": "No, I do not live alone. I live with my family.",
      "spoken_text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "original_text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "original_reference_text": "No, I do not live alone. I live with my family.",
      "display_question": "Q: Czy mieszkasz sam/sama?",
      "display_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "reference_question": "Q: Do you live alone?",
      "reference_answer": "A: No, I do not live alone. I live with my family.",
      "source_question": "Q: Czy mieszkasz sam/sama?",
      "source_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
      "output_file": "audio/0020-entry-0010-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0020-entry-0010-answer.mp3"
    },
    {
      "ordinal": 21,
      "entry_index": 11,
      "kind": "question",
      "display_text": "Dlaczego uczysz się języka polskiego?",
      "translation_text": "Why are you learning Polish?",
      "spoken_text": "Dlaczego uczysz się języka polskiego?",
      "text": "Dlaczego uczysz się języka polskiego?",
      "original_text": "Dlaczego uczysz się języka polskiego?",
      "original_reference_text": "Why are you learning Polish?",
      "display_question": "Q: Dlaczego uczysz się języka polskiego?",
      "display_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
      "reference_question": "Q: Why are you learning Polish?",
      "reference_answer": "A: I am learning Polish because I work in Poland.",
      "source_question": "Q: Dlaczego uczysz się języka polskiego?",
      "source_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
      "output_file": "audio/0021-entry-0011-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0021-entry-0011-question.mp3"
    },
    {
      "ordinal": 22,
      "entry_index": 11,
      "kind": "answer",
      "display_text": "Uczę się języka polskiego, bo pracuję w Polsce.",
      "translation_text": "I am learning Polish because I work in Poland.",
      "spoken_text": "Uczę się języka polskiego, bo pracuję w Polsce.",
      "text": "Uczę się języka polskiego, bo pracuję w Polsce.",
      "original_text": "Uczę się języka polskiego, bo pracuję w Polsce.",
      "original_reference_text": "I am learning Polish because I work in Poland.",
      "display_question": "Q: Dlaczego uczysz się języka polskiego?",
      "display_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
      "reference_question": "Q: Why are you learning Polish?",
      "reference_answer": "A: I am learning Polish because I work in Poland.",
      "source_question": "Q: Dlaczego uczysz się języka polskiego?",
      "source_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
      "output_file": "audio/0022-entry-0011-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0022-entry-0011-answer.mp3"
    },
    {
      "ordinal": 23,
      "entry_index": 12,
      "kind": "question",
      "display_text": "Dlaczego mieszkasz w Polsce?",
      "translation_text": "Why do you live in Poland?",
      "spoken_text": "Dlaczego mieszkasz w Polsce?",
      "text": "Dlaczego mieszkasz w Polsce?",
      "original_text": "Dlaczego mieszkasz w Polsce?",
      "original_reference_text": "Why do you live in Poland?",
      "display_question": "Q: Dlaczego mieszkasz w Polsce?",
      "display_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
      "reference_question": "Q: Why do you live in Poland?",
      "reference_answer": "A: I live in Poland because I have work here.",
      "source_question": "Q: Dlaczego mieszkasz w Polsce?",
      "source_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
      "output_file": "audio/0023-entry-0012-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0023-entry-0012-question.mp3"
    },
    {
      "ordinal": 24,
      "entry_index": 12,
      "kind": "answer",
      "display_text": "Mieszkam w Polsce, bo mam tutaj pracę.",
      "translation_text": "I live in Poland because I have work here.",
      "spoken_text": "Mieszkam w Polsce, bo mam tutaj pracę.",
      "text": "Mieszkam w Polsce, bo mam tutaj pracę.",
      "original_text": "Mieszkam w Polsce, bo mam tutaj pracę.",
      "original_reference_text": "I live in Poland because I have work here.",
      "display_question": "Q: Dlaczego mieszkasz w Polsce?",
      "display_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
      "reference_question": "Q: Why do you live in Poland?",
      "reference_answer": "A: I live in Poland because I have work here.",
      "source_question": "Q: Dlaczego mieszkasz w Polsce?",
      "source_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
      "output_file": "audio/0024-entry-0012-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0024-entry-0012-answer.mp3"
    },
    {
      "ordinal": 25,
      "entry_index": 13,
      "kind": "question",
      "display_text": "Co znaczy zapis adresu 17/20?",
      "translation_text": "What does the address format 17/20 mean?",
      "spoken_text": "Co znaczy zapis adresu 17/20?",
      "text": "Co znaczy zapis adresu 17/20?",
      "original_text": "Co znaczy zapis adresu 17/20?",
      "original_reference_text": "What does the address format 17/20 mean?",
      "display_question": "Q: Co znaczy zapis adresu 17/20?",
      "display_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
      "reference_question": "Q: What does the address format 17/20 mean?",
      "reference_answer": "A: 17 is the building number, and 20 is the apartment number.",
      "source_question": "Q: Co znaczy zapis adresu 17/20?",
      "source_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
      "output_file": "audio/0025-entry-0013-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0025-entry-0013-question.mp3"
    },
    {
      "ordinal": 26,
      "entry_index": 13,
      "kind": "answer",
      "display_text": "17 to numer budynku, a 20 to numer mieszkania.",
      "translation_text": "17 is the building number, and 20 is the apartment number.",
      "spoken_text": "17 to numer budynku, a 20 to numer mieszkania.",
      "text": "17 to numer budynku, a 20 to numer mieszkania.",
      "original_text": "17 to numer budynku, a 20 to numer mieszkania.",
      "original_reference_text": "17 is the building number, and 20 is the apartment number.",
      "display_question": "Q: Co znaczy zapis adresu 17/20?",
      "display_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
      "reference_question": "Q: What does the address format 17/20 mean?",
      "reference_answer": "A: 17 is the building number, and 20 is the apartment number.",
      "source_question": "Q: Co znaczy zapis adresu 17/20?",
      "source_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
      "output_file": "audio/0026-entry-0013-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0026-entry-0013-answer.mp3"
    },
    {
      "ordinal": 27,
      "entry_index": 14,
      "kind": "question",
      "display_text": "Co znaczy słowo nieruchomość?",
      "translation_text": "What does the word property mean?",
      "spoken_text": "Co znaczy słowo nieruchomość?",
      "text": "Co znaczy słowo nieruchomość?",
      "original_text": "Co znaczy słowo nieruchomość?",
      "original_reference_text": "What does the word property mean?",
      "display_question": "Q: Co znaczy słowo nieruchomość?",
      "display_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
      "reference_question": "Q: What does the word property mean?",
      "reference_answer": "A: Property means, for example, an apartment or a house.",
      "source_question": "Q: Co znaczy słowo nieruchomość?",
      "source_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
      "output_file": "audio/0027-entry-0014-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0027-entry-0014-question.mp3"
    },
    {
      "ordinal": 28,
      "entry_index": 14,
      "kind": "answer",
      "display_text": "Nieruchomość to na przykład mieszkanie albo dom.",
      "translation_text": "Property means, for example, an apartment or a house.",
      "spoken_text": "Nieruchomość to na przykład mieszkanie albo dom.",
      "text": "Nieruchomość to na przykład mieszkanie albo dom.",
      "original_text": "Nieruchomość to na przykład mieszkanie albo dom.",
      "original_reference_text": "Property means, for example, an apartment or a house.",
      "display_question": "Q: Co znaczy słowo nieruchomość?",
      "display_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
      "reference_question": "Q: What does the word property mean?",
      "reference_answer": "A: Property means, for example, an apartment or a house.",
      "source_question": "Q: Co znaczy słowo nieruchomość?",
      "source_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
      "output_file": "audio/0028-entry-0014-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0028-entry-0014-answer.mp3"
    },
    {
      "ordinal": 29,
      "entry_index": 15,
      "kind": "question",
      "display_text": "Jakie jest przeciwieństwo słowa wynajęty?",
      "translation_text": "What is the opposite of the word rented?",
      "spoken_text": "Jakie jest przeciwieństwo słowa wynajęty?",
      "text": "Jakie jest przeciwieństwo słowa wynajęty?",
      "original_text": "Jakie jest przeciwieństwo słowa wynajęty?",
      "original_reference_text": "What is the opposite of the word rented?",
      "display_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
      "display_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
      "reference_question": "Q: What is the opposite of the word rented?",
      "reference_answer": "A: The opposite of the word rented is owned.",
      "source_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
      "source_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
      "output_file": "audio/0029-entry-0015-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0029-entry-0015-question.mp3"
    },
    {
      "ordinal": 30,
      "entry_index": 15,
      "kind": "answer",
      "display_text": "Przeciwieństwo słowa wynajęty to własny.",
      "translation_text": "The opposite of the word rented is owned.",
      "spoken_text": "Przeciwieństwo słowa wynajęty to własny.",
      "text": "Przeciwieństwo słowa wynajęty to własny.",
      "original_text": "Przeciwieństwo słowa wynajęty to własny.",
      "original_reference_text": "The opposite of the word rented is owned.",
      "display_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
      "display_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
      "reference_question": "Q: What is the opposite of the word rented?",
      "reference_answer": "A: The opposite of the word rented is owned.",
      "source_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
      "source_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
      "output_file": "audio/0030-entry-0015-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0030-entry-0015-answer.mp3"
    },
    {
      "ordinal": 31,
      "entry_index": 16,
      "kind": "question",
      "display_text": "Jak odmienia się czasownik mieszkać?",
      "translation_text": "How is the verb to live conjugated?",
      "spoken_text": "Jak odmienia się czasownik mieszkać?",
      "text": "Jak odmienia się czasownik mieszkać?",
      "original_text": "Jak odmienia się czasownik mieszkać?",
      "original_reference_text": "How is the verb to live conjugated?",
      "display_question": "Q: Jak odmienia się czasownik mieszkać?",
      "display_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "reference_question": "Q: How is the verb to live conjugated?",
      "reference_answer": "A: I live, you live, he/she/it lives, we live.",
      "source_question": "Q: Jak odmienia się czasownik mieszkać?",
      "source_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "output_file": "audio/0031-entry-0016-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0031-entry-0016-question.mp3"
    },
    {
      "ordinal": 32,
      "entry_index": 16,
      "kind": "answer",
      "display_text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "translation_text": "I live, you live, he/she/it lives, we live.",
      "spoken_text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "original_text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "original_reference_text": "I live, you live, he/she/it lives, we live.",
      "display_question": "Q: Jak odmienia się czasownik mieszkać?",
      "display_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "reference_question": "Q: How is the verb to live conjugated?",
      "reference_answer": "A: I live, you live, he/she/it lives, we live.",
      "source_question": "Q: Jak odmienia się czasownik mieszkać?",
      "source_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
      "output_file": "audio/0032-entry-0016-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0032-entry-0016-answer.mp3"
    },
    {
      "ordinal": 33,
      "entry_index": 17,
      "kind": "question",
      "display_text": "Jak odmienia się czasownik mieć?",
      "translation_text": "How is the verb to have conjugated?",
      "spoken_text": "Jak odmienia się czasownik mieć?",
      "text": "Jak odmienia się czasownik mieć?",
      "original_text": "Jak odmienia się czasownik mieć?",
      "original_reference_text": "How is the verb to have conjugated?",
      "display_question": "Q: Jak odmienia się czasownik mieć?",
      "display_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "reference_question": "Q: How is the verb to have conjugated?",
      "reference_answer": "A: I have, you have, he/she/it has, we have.",
      "source_question": "Q: Jak odmienia się czasownik mieć?",
      "source_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "output_file": "audio/0033-entry-0017-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0033-entry-0017-question.mp3"
    },
    {
      "ordinal": 34,
      "entry_index": 17,
      "kind": "answer",
      "display_text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "translation_text": "I have, you have, he/she/it has, we have.",
      "spoken_text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "original_text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "original_reference_text": "I have, you have, he/she/it has, we have.",
      "display_question": "Q: Jak odmienia się czasownik mieć?",
      "display_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "reference_question": "Q: How is the verb to have conjugated?",
      "reference_answer": "A: I have, you have, he/she/it has, we have.",
      "source_question": "Q: Jak odmienia się czasownik mieć?",
      "source_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
      "output_file": "audio/0034-entry-0017-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0034-entry-0017-answer.mp3"
    },
    {
      "ordinal": 35,
      "entry_index": 18,
      "kind": "question",
      "display_text": "Jak odmienia się czasownik posiadać?",
      "translation_text": "How is the verb to possess conjugated?",
      "spoken_text": "Jak odmienia się czasownik posiadać?",
      "text": "Jak odmienia się czasownik posiadać?",
      "original_text": "Jak odmienia się czasownik posiadać?",
      "original_reference_text": "How is the verb to possess conjugated?",
      "display_question": "Q: Jak odmienia się czasownik posiadać?",
      "display_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "reference_question": "Q: How is the verb to possess conjugated?",
      "reference_answer": "A: I possess, you possess, he/she/it possesses, we possess.",
      "source_question": "Q: Jak odmienia się czasownik posiadać?",
      "source_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "output_file": "audio/0035-entry-0018-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0035-entry-0018-question.mp3"
    },
    {
      "ordinal": 36,
      "entry_index": 18,
      "kind": "answer",
      "display_text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "translation_text": "I possess, you possess, he/she/it possesses, we possess.",
      "spoken_text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "original_text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "original_reference_text": "I possess, you possess, he/she/it possesses, we possess.",
      "display_question": "Q: Jak odmienia się czasownik posiadać?",
      "display_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "reference_question": "Q: How is the verb to possess conjugated?",
      "reference_answer": "A: I possess, you possess, he/she/it possesses, we possess.",
      "source_question": "Q: Jak odmienia się czasownik posiadać?",
      "source_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
      "output_file": "audio/0036-entry-0018-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0036-entry-0018-answer.mp3"
    },
    {
      "ordinal": 37,
      "entry_index": 19,
      "kind": "question",
      "display_text": "Jak odmienia się czasownik wynajmować?",
      "translation_text": "How is the verb to rent conjugated?",
      "spoken_text": "Jak odmienia się czasownik wynajmować?",
      "text": "Jak odmienia się czasownik wynajmować?",
      "original_text": "Jak odmienia się czasownik wynajmować?",
      "original_reference_text": "How is the verb to rent conjugated?",
      "display_question": "Q: Jak odmienia się czasownik wynajmować?",
      "display_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "reference_question": "Q: How is the verb to rent conjugated?",
      "reference_answer": "A: I rent, you rent, he/she/it rents, we rent.",
      "source_question": "Q: Jak odmienia się czasownik wynajmować?",
      "source_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "output_file": "audio/0037-entry-0019-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0037-entry-0019-question.mp3"
    },
    {
      "ordinal": 38,
      "entry_index": 19,
      "kind": "answer",
      "display_text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "translation_text": "I rent, you rent, he/she/it rents, we rent.",
      "spoken_text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "original_text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "original_reference_text": "I rent, you rent, he/she/it rents, we rent.",
      "display_question": "Q: Jak odmienia się czasownik wynajmować?",
      "display_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "reference_question": "Q: How is the verb to rent conjugated?",
      "reference_answer": "A: I rent, you rent, he/she/it rents, we rent.",
      "source_question": "Q: Jak odmienia się czasownik wynajmować?",
      "source_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
      "output_file": "audio/0038-entry-0019-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0038-entry-0019-answer.mp3"
    },
    {
      "ordinal": 39,
      "entry_index": 20,
      "kind": "question",
      "display_text": "Jak odmienia się czasownik pracować?",
      "translation_text": "How is the verb to work conjugated?",
      "spoken_text": "Jak odmienia się czasownik pracować?",
      "text": "Jak odmienia się czasownik pracować?",
      "original_text": "Jak odmienia się czasownik pracować?",
      "original_reference_text": "How is the verb to work conjugated?",
      "display_question": "Q: Jak odmienia się czasownik pracować?",
      "display_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "reference_question": "Q: How is the verb to work conjugated?",
      "reference_answer": "A: I work, you work, he/she/it works, we work.",
      "source_question": "Q: Jak odmienia się czasownik pracować?",
      "source_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "output_file": "audio/0039-entry-0020-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0039-entry-0020-question.mp3"
    },
    {
      "ordinal": 40,
      "entry_index": 20,
      "kind": "answer",
      "display_text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "translation_text": "I work, you work, he/she/it works, we work.",
      "spoken_text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "original_text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "original_reference_text": "I work, you work, he/she/it works, we work.",
      "display_question": "Q: Jak odmienia się czasownik pracować?",
      "display_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "reference_question": "Q: How is the verb to work conjugated?",
      "reference_answer": "A: I work, you work, he/she/it works, we work.",
      "source_question": "Q: Jak odmienia się czasownik pracować?",
      "source_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
      "output_file": "audio/0040-entry-0020-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0040-entry-0020-answer.mp3"
    },
    {
      "ordinal": 41,
      "entry_index": 21,
      "kind": "question",
      "display_text": "Jak odmienia się czasownik uczyć się?",
      "translation_text": "How is the verb to learn conjugated?",
      "spoken_text": "Jak odmienia się czasownik uczyć się?",
      "text": "Jak odmienia się czasownik uczyć się?",
      "original_text": "Jak odmienia się czasownik uczyć się?",
      "original_reference_text": "How is the verb to learn conjugated?",
      "display_question": "Q: Jak odmienia się czasownik uczyć się?",
      "display_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "reference_question": "Q: How is the verb to learn conjugated?",
      "reference_answer": "A: I learn, you learn, he/she/it learns, we learn.",
      "source_question": "Q: Jak odmienia się czasownik uczyć się?",
      "source_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "output_file": "audio/0041-entry-0021-question.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0041-entry-0021-question.mp3"
    },
    {
      "ordinal": 42,
      "entry_index": 21,
      "kind": "answer",
      "display_text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "translation_text": "I learn, you learn, he/she/it learns, we learn.",
      "spoken_text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "original_text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "original_reference_text": "I learn, you learn, he/she/it learns, we learn.",
      "display_question": "Q: Jak odmienia się czasownik uczyć się?",
      "display_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "reference_question": "Q: How is the verb to learn conjugated?",
      "reference_answer": "A: I learn, you learn, he/she/it learns, we learn.",
      "source_question": "Q: Jak odmienia się czasownik uczyć się?",
      "source_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
      "output_file": "audio/0042-entry-0021-answer.mp3",
      "output_file_from_repo_root": "output-monika-pack/audio/0042-entry-0021-answer.mp3"
    }
  ]
};
window.__POLISH_MANIFEST__ = [
  {
    "ordinal": 1,
    "entry_index": 1,
    "kind": "question",
    "display_text": "Z kim pan/pani mieszka teraz?",
    "translation_text": "Who do you live with now?",
    "spoken_text": "Z kim pan/pani mieszka teraz?",
    "text": "Z kim pan/pani mieszka teraz?",
    "original_text": "Z kim pan/pani mieszka teraz?",
    "original_reference_text": "Who do you live with now?",
    "display_question": "Q: Z kim pan/pani mieszka teraz?",
    "display_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "reference_question": "Q: Who do you live with now?",
    "reference_answer": "A: I live with my family, that is my husband and my daughter.",
    "source_question": "Q: Z kim pan/pani mieszka teraz?",
    "source_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "output_file": "output-monika-pack/audio/0001-entry-0001-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0001-entry-0001-question.mp3"
  },
  {
    "ordinal": 2,
    "entry_index": 1,
    "kind": "answer",
    "display_text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "translation_text": "I live with my family, that is my husband and my daughter.",
    "spoken_text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "original_text": "Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "original_reference_text": "I live with my family, that is my husband and my daughter.",
    "display_question": "Q: Z kim pan/pani mieszka teraz?",
    "display_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "reference_question": "Q: Who do you live with now?",
    "reference_answer": "A: I live with my family, that is my husband and my daughter.",
    "source_question": "Q: Z kim pan/pani mieszka teraz?",
    "source_answer": "A: Mieszkam z moją rodziną, to jest mój mąż i moja córka.",
    "output_file": "output-monika-pack/audio/0002-entry-0001-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0002-entry-0001-answer.mp3"
  },
  {
    "ordinal": 3,
    "entry_index": 2,
    "kind": "question",
    "display_text": "Na jakim stanowisku pan/pani pracuje w firmie?",
    "translation_text": "What position do you work in at your company?",
    "spoken_text": "Na jakim stanowisku pan/pani pracuje w firmie?",
    "text": "Na jakim stanowisku pan/pani pracuje w firmie?",
    "original_text": "Na jakim stanowisku pan/pani pracuje w firmie?",
    "original_reference_text": "What position do you work in at your company?",
    "display_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
    "display_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
    "reference_question": "Q: What position do you work in at your company?",
    "reference_answer": "A: I work as a deputy director.",
    "source_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
    "source_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
    "output_file": "output-monika-pack/audio/0003-entry-0002-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0003-entry-0002-question.mp3"
  },
  {
    "ordinal": 4,
    "entry_index": 2,
    "kind": "answer",
    "display_text": "Pracuję na stanowisku zastępcy dyrektora.",
    "translation_text": "I work as a deputy director.",
    "spoken_text": "Pracuję na stanowisku zastępcy dyrektora.",
    "text": "Pracuję na stanowisku zastępcy dyrektora.",
    "original_text": "Pracuję na stanowisku zastępcy dyrektora.",
    "original_reference_text": "I work as a deputy director.",
    "display_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
    "display_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
    "reference_question": "Q: What position do you work in at your company?",
    "reference_answer": "A: I work as a deputy director.",
    "source_question": "Q: Na jakim stanowisku pan/pani pracuje w firmie?",
    "source_answer": "A: Pracuję na stanowisku zastępcy dyrektora.",
    "output_file": "output-monika-pack/audio/0004-entry-0002-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0004-entry-0002-answer.mp3"
  },
  {
    "ordinal": 5,
    "entry_index": 3,
    "kind": "question",
    "display_text": "Gdzie pani pracuje, w domu online czy w biurze?",
    "translation_text": "Where do you work, from home online or in the office?",
    "spoken_text": "Gdzie pani pracuje, w domu online czy w biurze?",
    "text": "Gdzie pani pracuje, w domu online czy w biurze?",
    "original_text": "Gdzie pani pracuje, w domu online czy w biurze?",
    "original_reference_text": "Where do you work, from home online or in the office?",
    "display_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
    "display_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "reference_question": "Q: Where do you work, from home online or in the office?",
    "reference_answer": "A: I work from home two days a week and in the office three days a week.",
    "source_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
    "source_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "output_file": "output-monika-pack/audio/0005-entry-0003-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0005-entry-0003-question.mp3"
  },
  {
    "ordinal": 6,
    "entry_index": 3,
    "kind": "answer",
    "display_text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "translation_text": "I work from home two days a week and in the office three days a week.",
    "spoken_text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "original_text": "Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "original_reference_text": "I work from home two days a week and in the office three days a week.",
    "display_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
    "display_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "reference_question": "Q: Where do you work, from home online or in the office?",
    "reference_answer": "A: I work from home two days a week and in the office three days a week.",
    "source_question": "Q: Gdzie pani pracuje, w domu online czy w biurze?",
    "source_answer": "A: Dwa dni w tygodniu pracuję w domu i trzy dni w tygodniu pracuję w biurze.",
    "output_file": "output-monika-pack/audio/0006-entry-0003-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0006-entry-0003-answer.mp3"
  },
  {
    "ordinal": 7,
    "entry_index": 4,
    "kind": "question",
    "display_text": "Pod jakim adresem mieszkasz?",
    "translation_text": "What address do you live at?",
    "spoken_text": "Pod jakim adresem mieszkasz?",
    "text": "Pod jakim adresem mieszkasz?",
    "original_text": "Pod jakim adresem mieszkasz?",
    "original_reference_text": "What address do you live at?",
    "display_question": "Q: Pod jakim adresem mieszkasz?",
    "display_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "reference_question": "Q: What address do you live at?",
    "reference_answer": "A: I currently live in Krakow at osiedle Piastów 56C/120.",
    "source_question": "Q: Pod jakim adresem mieszkasz?",
    "source_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "output_file": "output-monika-pack/audio/0007-entry-0004-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0007-entry-0004-question.mp3"
  },
  {
    "ordinal": 8,
    "entry_index": 4,
    "kind": "answer",
    "display_text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "translation_text": "I currently live in Krakow at osiedle Piastów 56C/120.",
    "spoken_text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "original_text": "Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "original_reference_text": "I currently live in Krakow at osiedle Piastów 56C/120.",
    "display_question": "Q: Pod jakim adresem mieszkasz?",
    "display_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "reference_question": "Q: What address do you live at?",
    "reference_answer": "A: I currently live in Krakow at osiedle Piastów 56C/120.",
    "source_question": "Q: Pod jakim adresem mieszkasz?",
    "source_answer": "A: Aktualnie mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "output_file": "output-monika-pack/audio/0008-entry-0004-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0008-entry-0004-answer.mp3"
  },
  {
    "ordinal": 9,
    "entry_index": 5,
    "kind": "question",
    "display_text": "Gdzie mieszkasz?",
    "translation_text": "Where do you live?",
    "spoken_text": "Gdzie mieszkasz?",
    "text": "Gdzie mieszkasz?",
    "original_text": "Gdzie mieszkasz?",
    "original_reference_text": "Where do you live?",
    "display_question": "Q: Gdzie mieszkasz?",
    "display_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "reference_question": "Q: Where do you live?",
    "reference_answer": "A: I live in Krakow at osiedle Piastów 56C/120.",
    "source_question": "Q: Gdzie mieszkasz?",
    "source_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "output_file": "output-monika-pack/audio/0009-entry-0005-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0009-entry-0005-question.mp3"
  },
  {
    "ordinal": 10,
    "entry_index": 5,
    "kind": "answer",
    "display_text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "translation_text": "I live in Krakow at osiedle Piastów 56C/120.",
    "spoken_text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "original_text": "Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "original_reference_text": "I live in Krakow at osiedle Piastów 56C/120.",
    "display_question": "Q: Gdzie mieszkasz?",
    "display_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "reference_question": "Q: Where do you live?",
    "reference_answer": "A: I live in Krakow at osiedle Piastów 56C/120.",
    "source_question": "Q: Gdzie mieszkasz?",
    "source_answer": "A: Mieszkam w Krakowie na osiedlu Piastów 56C/120.",
    "output_file": "output-monika-pack/audio/0010-entry-0005-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0010-entry-0005-answer.mp3"
  },
  {
    "ordinal": 11,
    "entry_index": 6,
    "kind": "question",
    "display_text": "Jaki jest twój obecny adres?",
    "translation_text": "What is your current address?",
    "spoken_text": "Jaki jest twój obecny adres?",
    "text": "Jaki jest twój obecny adres?",
    "original_text": "Jaki jest twój obecny adres?",
    "original_reference_text": "What is your current address?",
    "display_question": "Q: Jaki jest twój obecny adres?",
    "display_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
    "reference_question": "Q: What is your current address?",
    "reference_answer": "A: My current address is: osiedle Piastów 56C/120.",
    "source_question": "Q: Jaki jest twój obecny adres?",
    "source_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
    "output_file": "output-monika-pack/audio/0011-entry-0006-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0011-entry-0006-question.mp3"
  },
  {
    "ordinal": 12,
    "entry_index": 6,
    "kind": "answer",
    "display_text": "Mój obecny adres to: osiedle Piastów 56C/120.",
    "translation_text": "My current address is: osiedle Piastów 56C/120.",
    "spoken_text": "Mój obecny adres to: osiedle Piastów 56C/120.",
    "text": "Mój obecny adres to: osiedle Piastów 56C/120.",
    "original_text": "Mój obecny adres to: osiedle Piastów 56C/120.",
    "original_reference_text": "My current address is: osiedle Piastów 56C/120.",
    "display_question": "Q: Jaki jest twój obecny adres?",
    "display_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
    "reference_question": "Q: What is your current address?",
    "reference_answer": "A: My current address is: osiedle Piastów 56C/120.",
    "source_question": "Q: Jaki jest twój obecny adres?",
    "source_answer": "A: Mój obecny adres to: osiedle Piastów 56C/120.",
    "output_file": "output-monika-pack/audio/0012-entry-0006-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0012-entry-0006-answer.mp3"
  },
  {
    "ordinal": 13,
    "entry_index": 7,
    "kind": "question",
    "display_text": "Czy mieszkasz w wynajętym mieszkaniu?",
    "translation_text": "Are you staying in a rental property?",
    "spoken_text": "Czy mieszkasz w wynajętym mieszkaniu?",
    "text": "Czy mieszkasz w wynajętym mieszkaniu?",
    "original_text": "Czy mieszkasz w wynajętym mieszkaniu?",
    "original_reference_text": "Are you staying in a rental property?",
    "display_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
    "display_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "reference_question": "Q: Are you staying in a rental property?",
    "reference_answer": "A: No, I do not rent. This is my own apartment.",
    "source_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
    "source_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "output_file": "output-monika-pack/audio/0013-entry-0007-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0013-entry-0007-question.mp3"
  },
  {
    "ordinal": 14,
    "entry_index": 7,
    "kind": "answer",
    "display_text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "translation_text": "No, I do not rent. This is my own apartment.",
    "spoken_text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "original_text": "Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "original_reference_text": "No, I do not rent. This is my own apartment.",
    "display_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
    "display_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "reference_question": "Q: Are you staying in a rental property?",
    "reference_answer": "A: No, I do not rent. This is my own apartment.",
    "source_question": "Q: Czy mieszkasz w wynajętym mieszkaniu?",
    "source_answer": "A: Nie, nie wynajmuję. To jest moje własne mieszkanie.",
    "output_file": "output-monika-pack/audio/0014-entry-0007-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0014-entry-0007-answer.mp3"
  },
  {
    "ordinal": 15,
    "entry_index": 8,
    "kind": "question",
    "display_text": "Czy wynajmujesz mieszkanie?",
    "translation_text": "Do you rent an apartment?",
    "spoken_text": "Czy wynajmujesz mieszkanie?",
    "text": "Czy wynajmujesz mieszkanie?",
    "original_text": "Czy wynajmujesz mieszkanie?",
    "original_reference_text": "Do you rent an apartment?",
    "display_question": "Q: Czy wynajmujesz mieszkanie?",
    "display_answer": "A: Tak, wynajmuję mieszkanie.",
    "reference_question": "Q: Do you rent an apartment?",
    "reference_answer": "A: Yes, I rent an apartment.",
    "source_question": "Q: Czy wynajmujesz mieszkanie?",
    "source_answer": "A: Tak, wynajmuję mieszkanie.",
    "output_file": "output-monika-pack/audio/0015-entry-0008-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0015-entry-0008-question.mp3"
  },
  {
    "ordinal": 16,
    "entry_index": 8,
    "kind": "answer",
    "display_text": "Tak, wynajmuję mieszkanie.",
    "translation_text": "Yes, I rent an apartment.",
    "spoken_text": "Tak, wynajmuję mieszkanie.",
    "text": "Tak, wynajmuję mieszkanie.",
    "original_text": "Tak, wynajmuję mieszkanie.",
    "original_reference_text": "Yes, I rent an apartment.",
    "display_question": "Q: Czy wynajmujesz mieszkanie?",
    "display_answer": "A: Tak, wynajmuję mieszkanie.",
    "reference_question": "Q: Do you rent an apartment?",
    "reference_answer": "A: Yes, I rent an apartment.",
    "source_question": "Q: Czy wynajmujesz mieszkanie?",
    "source_answer": "A: Tak, wynajmuję mieszkanie.",
    "output_file": "output-monika-pack/audio/0016-entry-0008-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0016-entry-0008-answer.mp3"
  },
  {
    "ordinal": 17,
    "entry_index": 9,
    "kind": "question",
    "display_text": "Czy posiadasz własną nieruchomość?",
    "translation_text": "Do you own a property?",
    "spoken_text": "Czy posiadasz własną nieruchomość?",
    "text": "Czy posiadasz własną nieruchomość?",
    "original_text": "Czy posiadasz własną nieruchomość?",
    "original_reference_text": "Do you own a property?",
    "display_question": "Q: Czy posiadasz własną nieruchomość?",
    "display_answer": "A: Tak, mam własną nieruchomość.",
    "reference_question": "Q: Do you own a property?",
    "reference_answer": "A: Yes, I own a property.",
    "source_question": "Q: Czy posiadasz własną nieruchomość?",
    "source_answer": "A: Tak, mam własną nieruchomość.",
    "output_file": "output-monika-pack/audio/0017-entry-0009-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0017-entry-0009-question.mp3"
  },
  {
    "ordinal": 18,
    "entry_index": 9,
    "kind": "answer",
    "display_text": "Tak, mam własną nieruchomość.",
    "translation_text": "Yes, I own a property.",
    "spoken_text": "Tak, mam własną nieruchomość.",
    "text": "Tak, mam własną nieruchomość.",
    "original_text": "Tak, mam własną nieruchomość.",
    "original_reference_text": "Yes, I own a property.",
    "display_question": "Q: Czy posiadasz własną nieruchomość?",
    "display_answer": "A: Tak, mam własną nieruchomość.",
    "reference_question": "Q: Do you own a property?",
    "reference_answer": "A: Yes, I own a property.",
    "source_question": "Q: Czy posiadasz własną nieruchomość?",
    "source_answer": "A: Tak, mam własną nieruchomość.",
    "output_file": "output-monika-pack/audio/0018-entry-0009-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0018-entry-0009-answer.mp3"
  },
  {
    "ordinal": 19,
    "entry_index": 10,
    "kind": "question",
    "display_text": "Czy mieszkasz sam/sama?",
    "translation_text": "Do you live alone?",
    "spoken_text": "Czy mieszkasz sam/sama?",
    "text": "Czy mieszkasz sam/sama?",
    "original_text": "Czy mieszkasz sam/sama?",
    "original_reference_text": "Do you live alone?",
    "display_question": "Q: Czy mieszkasz sam/sama?",
    "display_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "reference_question": "Q: Do you live alone?",
    "reference_answer": "A: No, I do not live alone. I live with my family.",
    "source_question": "Q: Czy mieszkasz sam/sama?",
    "source_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "output_file": "output-monika-pack/audio/0019-entry-0010-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0019-entry-0010-question.mp3"
  },
  {
    "ordinal": 20,
    "entry_index": 10,
    "kind": "answer",
    "display_text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "translation_text": "No, I do not live alone. I live with my family.",
    "spoken_text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "original_text": "Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "original_reference_text": "No, I do not live alone. I live with my family.",
    "display_question": "Q: Czy mieszkasz sam/sama?",
    "display_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "reference_question": "Q: Do you live alone?",
    "reference_answer": "A: No, I do not live alone. I live with my family.",
    "source_question": "Q: Czy mieszkasz sam/sama?",
    "source_answer": "A: Nie, nie mieszkam sam/sama. Mieszkam z moją rodziną.",
    "output_file": "output-monika-pack/audio/0020-entry-0010-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0020-entry-0010-answer.mp3"
  },
  {
    "ordinal": 21,
    "entry_index": 11,
    "kind": "question",
    "display_text": "Dlaczego uczysz się języka polskiego?",
    "translation_text": "Why are you learning Polish?",
    "spoken_text": "Dlaczego uczysz się języka polskiego?",
    "text": "Dlaczego uczysz się języka polskiego?",
    "original_text": "Dlaczego uczysz się języka polskiego?",
    "original_reference_text": "Why are you learning Polish?",
    "display_question": "Q: Dlaczego uczysz się języka polskiego?",
    "display_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
    "reference_question": "Q: Why are you learning Polish?",
    "reference_answer": "A: I am learning Polish because I work in Poland.",
    "source_question": "Q: Dlaczego uczysz się języka polskiego?",
    "source_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
    "output_file": "output-monika-pack/audio/0021-entry-0011-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0021-entry-0011-question.mp3"
  },
  {
    "ordinal": 22,
    "entry_index": 11,
    "kind": "answer",
    "display_text": "Uczę się języka polskiego, bo pracuję w Polsce.",
    "translation_text": "I am learning Polish because I work in Poland.",
    "spoken_text": "Uczę się języka polskiego, bo pracuję w Polsce.",
    "text": "Uczę się języka polskiego, bo pracuję w Polsce.",
    "original_text": "Uczę się języka polskiego, bo pracuję w Polsce.",
    "original_reference_text": "I am learning Polish because I work in Poland.",
    "display_question": "Q: Dlaczego uczysz się języka polskiego?",
    "display_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
    "reference_question": "Q: Why are you learning Polish?",
    "reference_answer": "A: I am learning Polish because I work in Poland.",
    "source_question": "Q: Dlaczego uczysz się języka polskiego?",
    "source_answer": "A: Uczę się języka polskiego, bo pracuję w Polsce.",
    "output_file": "output-monika-pack/audio/0022-entry-0011-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0022-entry-0011-answer.mp3"
  },
  {
    "ordinal": 23,
    "entry_index": 12,
    "kind": "question",
    "display_text": "Dlaczego mieszkasz w Polsce?",
    "translation_text": "Why do you live in Poland?",
    "spoken_text": "Dlaczego mieszkasz w Polsce?",
    "text": "Dlaczego mieszkasz w Polsce?",
    "original_text": "Dlaczego mieszkasz w Polsce?",
    "original_reference_text": "Why do you live in Poland?",
    "display_question": "Q: Dlaczego mieszkasz w Polsce?",
    "display_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
    "reference_question": "Q: Why do you live in Poland?",
    "reference_answer": "A: I live in Poland because I have work here.",
    "source_question": "Q: Dlaczego mieszkasz w Polsce?",
    "source_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
    "output_file": "output-monika-pack/audio/0023-entry-0012-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0023-entry-0012-question.mp3"
  },
  {
    "ordinal": 24,
    "entry_index": 12,
    "kind": "answer",
    "display_text": "Mieszkam w Polsce, bo mam tutaj pracę.",
    "translation_text": "I live in Poland because I have work here.",
    "spoken_text": "Mieszkam w Polsce, bo mam tutaj pracę.",
    "text": "Mieszkam w Polsce, bo mam tutaj pracę.",
    "original_text": "Mieszkam w Polsce, bo mam tutaj pracę.",
    "original_reference_text": "I live in Poland because I have work here.",
    "display_question": "Q: Dlaczego mieszkasz w Polsce?",
    "display_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
    "reference_question": "Q: Why do you live in Poland?",
    "reference_answer": "A: I live in Poland because I have work here.",
    "source_question": "Q: Dlaczego mieszkasz w Polsce?",
    "source_answer": "A: Mieszkam w Polsce, bo mam tutaj pracę.",
    "output_file": "output-monika-pack/audio/0024-entry-0012-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0024-entry-0012-answer.mp3"
  },
  {
    "ordinal": 25,
    "entry_index": 13,
    "kind": "question",
    "display_text": "Co znaczy zapis adresu 17/20?",
    "translation_text": "What does the address format 17/20 mean?",
    "spoken_text": "Co znaczy zapis adresu 17/20?",
    "text": "Co znaczy zapis adresu 17/20?",
    "original_text": "Co znaczy zapis adresu 17/20?",
    "original_reference_text": "What does the address format 17/20 mean?",
    "display_question": "Q: Co znaczy zapis adresu 17/20?",
    "display_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
    "reference_question": "Q: What does the address format 17/20 mean?",
    "reference_answer": "A: 17 is the building number, and 20 is the apartment number.",
    "source_question": "Q: Co znaczy zapis adresu 17/20?",
    "source_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
    "output_file": "output-monika-pack/audio/0025-entry-0013-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0025-entry-0013-question.mp3"
  },
  {
    "ordinal": 26,
    "entry_index": 13,
    "kind": "answer",
    "display_text": "17 to numer budynku, a 20 to numer mieszkania.",
    "translation_text": "17 is the building number, and 20 is the apartment number.",
    "spoken_text": "17 to numer budynku, a 20 to numer mieszkania.",
    "text": "17 to numer budynku, a 20 to numer mieszkania.",
    "original_text": "17 to numer budynku, a 20 to numer mieszkania.",
    "original_reference_text": "17 is the building number, and 20 is the apartment number.",
    "display_question": "Q: Co znaczy zapis adresu 17/20?",
    "display_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
    "reference_question": "Q: What does the address format 17/20 mean?",
    "reference_answer": "A: 17 is the building number, and 20 is the apartment number.",
    "source_question": "Q: Co znaczy zapis adresu 17/20?",
    "source_answer": "A: 17 to numer budynku, a 20 to numer mieszkania.",
    "output_file": "output-monika-pack/audio/0026-entry-0013-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0026-entry-0013-answer.mp3"
  },
  {
    "ordinal": 27,
    "entry_index": 14,
    "kind": "question",
    "display_text": "Co znaczy słowo nieruchomość?",
    "translation_text": "What does the word property mean?",
    "spoken_text": "Co znaczy słowo nieruchomość?",
    "text": "Co znaczy słowo nieruchomość?",
    "original_text": "Co znaczy słowo nieruchomość?",
    "original_reference_text": "What does the word property mean?",
    "display_question": "Q: Co znaczy słowo nieruchomość?",
    "display_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
    "reference_question": "Q: What does the word property mean?",
    "reference_answer": "A: Property means, for example, an apartment or a house.",
    "source_question": "Q: Co znaczy słowo nieruchomość?",
    "source_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
    "output_file": "output-monika-pack/audio/0027-entry-0014-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0027-entry-0014-question.mp3"
  },
  {
    "ordinal": 28,
    "entry_index": 14,
    "kind": "answer",
    "display_text": "Nieruchomość to na przykład mieszkanie albo dom.",
    "translation_text": "Property means, for example, an apartment or a house.",
    "spoken_text": "Nieruchomość to na przykład mieszkanie albo dom.",
    "text": "Nieruchomość to na przykład mieszkanie albo dom.",
    "original_text": "Nieruchomość to na przykład mieszkanie albo dom.",
    "original_reference_text": "Property means, for example, an apartment or a house.",
    "display_question": "Q: Co znaczy słowo nieruchomość?",
    "display_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
    "reference_question": "Q: What does the word property mean?",
    "reference_answer": "A: Property means, for example, an apartment or a house.",
    "source_question": "Q: Co znaczy słowo nieruchomość?",
    "source_answer": "A: Nieruchomość to na przykład mieszkanie albo dom.",
    "output_file": "output-monika-pack/audio/0028-entry-0014-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0028-entry-0014-answer.mp3"
  },
  {
    "ordinal": 29,
    "entry_index": 15,
    "kind": "question",
    "display_text": "Jakie jest przeciwieństwo słowa wynajęty?",
    "translation_text": "What is the opposite of the word rented?",
    "spoken_text": "Jakie jest przeciwieństwo słowa wynajęty?",
    "text": "Jakie jest przeciwieństwo słowa wynajęty?",
    "original_text": "Jakie jest przeciwieństwo słowa wynajęty?",
    "original_reference_text": "What is the opposite of the word rented?",
    "display_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
    "display_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
    "reference_question": "Q: What is the opposite of the word rented?",
    "reference_answer": "A: The opposite of the word rented is owned.",
    "source_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
    "source_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
    "output_file": "output-monika-pack/audio/0029-entry-0015-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0029-entry-0015-question.mp3"
  },
  {
    "ordinal": 30,
    "entry_index": 15,
    "kind": "answer",
    "display_text": "Przeciwieństwo słowa wynajęty to własny.",
    "translation_text": "The opposite of the word rented is owned.",
    "spoken_text": "Przeciwieństwo słowa wynajęty to własny.",
    "text": "Przeciwieństwo słowa wynajęty to własny.",
    "original_text": "Przeciwieństwo słowa wynajęty to własny.",
    "original_reference_text": "The opposite of the word rented is owned.",
    "display_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
    "display_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
    "reference_question": "Q: What is the opposite of the word rented?",
    "reference_answer": "A: The opposite of the word rented is owned.",
    "source_question": "Q: Jakie jest przeciwieństwo słowa wynajęty?",
    "source_answer": "A: Przeciwieństwo słowa wynajęty to własny.",
    "output_file": "output-monika-pack/audio/0030-entry-0015-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0030-entry-0015-answer.mp3"
  },
  {
    "ordinal": 31,
    "entry_index": 16,
    "kind": "question",
    "display_text": "Jak odmienia się czasownik mieszkać?",
    "translation_text": "How is the verb to live conjugated?",
    "spoken_text": "Jak odmienia się czasownik mieszkać?",
    "text": "Jak odmienia się czasownik mieszkać?",
    "original_text": "Jak odmienia się czasownik mieszkać?",
    "original_reference_text": "How is the verb to live conjugated?",
    "display_question": "Q: Jak odmienia się czasownik mieszkać?",
    "display_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "reference_question": "Q: How is the verb to live conjugated?",
    "reference_answer": "A: I live, you live, he/she/it lives, we live.",
    "source_question": "Q: Jak odmienia się czasownik mieszkać?",
    "source_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "output_file": "output-monika-pack/audio/0031-entry-0016-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0031-entry-0016-question.mp3"
  },
  {
    "ordinal": 32,
    "entry_index": 16,
    "kind": "answer",
    "display_text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "translation_text": "I live, you live, he/she/it lives, we live.",
    "spoken_text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "original_text": "Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "original_reference_text": "I live, you live, he/she/it lives, we live.",
    "display_question": "Q: Jak odmienia się czasownik mieszkać?",
    "display_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "reference_question": "Q: How is the verb to live conjugated?",
    "reference_answer": "A: I live, you live, he/she/it lives, we live.",
    "source_question": "Q: Jak odmienia się czasownik mieszkać?",
    "source_answer": "A: Ja mieszkam, ty mieszkasz, on/ona/ono mieszka, my mieszkamy.",
    "output_file": "output-monika-pack/audio/0032-entry-0016-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0032-entry-0016-answer.mp3"
  },
  {
    "ordinal": 33,
    "entry_index": 17,
    "kind": "question",
    "display_text": "Jak odmienia się czasownik mieć?",
    "translation_text": "How is the verb to have conjugated?",
    "spoken_text": "Jak odmienia się czasownik mieć?",
    "text": "Jak odmienia się czasownik mieć?",
    "original_text": "Jak odmienia się czasownik mieć?",
    "original_reference_text": "How is the verb to have conjugated?",
    "display_question": "Q: Jak odmienia się czasownik mieć?",
    "display_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "reference_question": "Q: How is the verb to have conjugated?",
    "reference_answer": "A: I have, you have, he/she/it has, we have.",
    "source_question": "Q: Jak odmienia się czasownik mieć?",
    "source_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "output_file": "output-monika-pack/audio/0033-entry-0017-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0033-entry-0017-question.mp3"
  },
  {
    "ordinal": 34,
    "entry_index": 17,
    "kind": "answer",
    "display_text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "translation_text": "I have, you have, he/she/it has, we have.",
    "spoken_text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "original_text": "Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "original_reference_text": "I have, you have, he/she/it has, we have.",
    "display_question": "Q: Jak odmienia się czasownik mieć?",
    "display_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "reference_question": "Q: How is the verb to have conjugated?",
    "reference_answer": "A: I have, you have, he/she/it has, we have.",
    "source_question": "Q: Jak odmienia się czasownik mieć?",
    "source_answer": "A: Ja mam, ty masz, on/ona/ono ma, my mamy.",
    "output_file": "output-monika-pack/audio/0034-entry-0017-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0034-entry-0017-answer.mp3"
  },
  {
    "ordinal": 35,
    "entry_index": 18,
    "kind": "question",
    "display_text": "Jak odmienia się czasownik posiadać?",
    "translation_text": "How is the verb to possess conjugated?",
    "spoken_text": "Jak odmienia się czasownik posiadać?",
    "text": "Jak odmienia się czasownik posiadać?",
    "original_text": "Jak odmienia się czasownik posiadać?",
    "original_reference_text": "How is the verb to possess conjugated?",
    "display_question": "Q: Jak odmienia się czasownik posiadać?",
    "display_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "reference_question": "Q: How is the verb to possess conjugated?",
    "reference_answer": "A: I possess, you possess, he/she/it possesses, we possess.",
    "source_question": "Q: Jak odmienia się czasownik posiadać?",
    "source_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "output_file": "output-monika-pack/audio/0035-entry-0018-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0035-entry-0018-question.mp3"
  },
  {
    "ordinal": 36,
    "entry_index": 18,
    "kind": "answer",
    "display_text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "translation_text": "I possess, you possess, he/she/it possesses, we possess.",
    "spoken_text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "original_text": "Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "original_reference_text": "I possess, you possess, he/she/it possesses, we possess.",
    "display_question": "Q: Jak odmienia się czasownik posiadać?",
    "display_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "reference_question": "Q: How is the verb to possess conjugated?",
    "reference_answer": "A: I possess, you possess, he/she/it possesses, we possess.",
    "source_question": "Q: Jak odmienia się czasownik posiadać?",
    "source_answer": "A: Ja posiadam, ty posiadasz, on/ona/ono posiada, my posiadamy.",
    "output_file": "output-monika-pack/audio/0036-entry-0018-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0036-entry-0018-answer.mp3"
  },
  {
    "ordinal": 37,
    "entry_index": 19,
    "kind": "question",
    "display_text": "Jak odmienia się czasownik wynajmować?",
    "translation_text": "How is the verb to rent conjugated?",
    "spoken_text": "Jak odmienia się czasownik wynajmować?",
    "text": "Jak odmienia się czasownik wynajmować?",
    "original_text": "Jak odmienia się czasownik wynajmować?",
    "original_reference_text": "How is the verb to rent conjugated?",
    "display_question": "Q: Jak odmienia się czasownik wynajmować?",
    "display_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "reference_question": "Q: How is the verb to rent conjugated?",
    "reference_answer": "A: I rent, you rent, he/she/it rents, we rent.",
    "source_question": "Q: Jak odmienia się czasownik wynajmować?",
    "source_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "output_file": "output-monika-pack/audio/0037-entry-0019-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0037-entry-0019-question.mp3"
  },
  {
    "ordinal": 38,
    "entry_index": 19,
    "kind": "answer",
    "display_text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "translation_text": "I rent, you rent, he/she/it rents, we rent.",
    "spoken_text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "original_text": "Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "original_reference_text": "I rent, you rent, he/she/it rents, we rent.",
    "display_question": "Q: Jak odmienia się czasownik wynajmować?",
    "display_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "reference_question": "Q: How is the verb to rent conjugated?",
    "reference_answer": "A: I rent, you rent, he/she/it rents, we rent.",
    "source_question": "Q: Jak odmienia się czasownik wynajmować?",
    "source_answer": "A: Ja wynajmuję, ty wynajmujesz, on/ona/ono wynajmuje, my wynajmujemy.",
    "output_file": "output-monika-pack/audio/0038-entry-0019-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0038-entry-0019-answer.mp3"
  },
  {
    "ordinal": 39,
    "entry_index": 20,
    "kind": "question",
    "display_text": "Jak odmienia się czasownik pracować?",
    "translation_text": "How is the verb to work conjugated?",
    "spoken_text": "Jak odmienia się czasownik pracować?",
    "text": "Jak odmienia się czasownik pracować?",
    "original_text": "Jak odmienia się czasownik pracować?",
    "original_reference_text": "How is the verb to work conjugated?",
    "display_question": "Q: Jak odmienia się czasownik pracować?",
    "display_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "reference_question": "Q: How is the verb to work conjugated?",
    "reference_answer": "A: I work, you work, he/she/it works, we work.",
    "source_question": "Q: Jak odmienia się czasownik pracować?",
    "source_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "output_file": "output-monika-pack/audio/0039-entry-0020-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0039-entry-0020-question.mp3"
  },
  {
    "ordinal": 40,
    "entry_index": 20,
    "kind": "answer",
    "display_text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "translation_text": "I work, you work, he/she/it works, we work.",
    "spoken_text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "original_text": "Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "original_reference_text": "I work, you work, he/she/it works, we work.",
    "display_question": "Q: Jak odmienia się czasownik pracować?",
    "display_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "reference_question": "Q: How is the verb to work conjugated?",
    "reference_answer": "A: I work, you work, he/she/it works, we work.",
    "source_question": "Q: Jak odmienia się czasownik pracować?",
    "source_answer": "A: Ja pracuję, ty pracujesz, on/ona/ono pracuje, my pracujemy.",
    "output_file": "output-monika-pack/audio/0040-entry-0020-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0040-entry-0020-answer.mp3"
  },
  {
    "ordinal": 41,
    "entry_index": 21,
    "kind": "question",
    "display_text": "Jak odmienia się czasownik uczyć się?",
    "translation_text": "How is the verb to learn conjugated?",
    "spoken_text": "Jak odmienia się czasownik uczyć się?",
    "text": "Jak odmienia się czasownik uczyć się?",
    "original_text": "Jak odmienia się czasownik uczyć się?",
    "original_reference_text": "How is the verb to learn conjugated?",
    "display_question": "Q: Jak odmienia się czasownik uczyć się?",
    "display_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "reference_question": "Q: How is the verb to learn conjugated?",
    "reference_answer": "A: I learn, you learn, he/she/it learns, we learn.",
    "source_question": "Q: Jak odmienia się czasownik uczyć się?",
    "source_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "output_file": "output-monika-pack/audio/0041-entry-0021-question.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0041-entry-0021-question.mp3"
  },
  {
    "ordinal": 42,
    "entry_index": 21,
    "kind": "answer",
    "display_text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "translation_text": "I learn, you learn, he/she/it learns, we learn.",
    "spoken_text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "original_text": "Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "original_reference_text": "I learn, you learn, he/she/it learns, we learn.",
    "display_question": "Q: Jak odmienia się czasownik uczyć się?",
    "display_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "reference_question": "Q: How is the verb to learn conjugated?",
    "reference_answer": "A: I learn, you learn, he/she/it learns, we learn.",
    "source_question": "Q: Jak odmienia się czasownik uczyć się?",
    "source_answer": "A: Ja uczę się, ty uczysz się, on/ona/ono uczy się, my uczymy się.",
    "output_file": "output-monika-pack/audio/0042-entry-0021-answer.mp3",
    "output_file_from_repo_root": "output-monika-pack/audio/0042-entry-0021-answer.mp3"
  }
];
