window.__LANGUAGE_LEARNING_BUNDLE__ = {
  "meta": {
    "schema_version": "2.0",
    "generated_at": "2026-07-16T22:36:53.369876+00:00",
    "input_file": "content/urzad-basic-responses-qa.txt",
    "study_column": 0,
    "reference_column": 1,
    "mode": "both",
    "voice": "pl-PL-ZofiaNeural",
    "study_language_name": "Polish",
    "reference_language_name": "English",
    "dashboard_title": "Urząd Basic Response Practice",
    "dashboard_subtitle": "Practice very basic interview fallback phrases with translations and Polish audio.",
    "output_dir_name": "output-urzad-basic-pack",
    "profile_file": null,
    "pronunciation_file": null,
    "entry_count": 5,
    "item_count": 10
  },
  "items": [
    {
      "ordinal": 1,
      "entry_index": 1,
      "kind": "question",
      "display_text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "translation_text": "What will you say if you do not remember something?",
      "spoken_text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "original_text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "original_reference_text": "What will you say if you do not remember something?",
      "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "display_answer": "A: Nie pamiętam.",
      "reference_question": "Q: What will you say if you do not remember something?",
      "reference_answer": "A: I do not remember.",
      "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "source_answer": "A: Nie pamiętam.",
      "output_file": "audio/0001-entry-0001-question.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0001-entry-0001-question.mp3"
    },
    {
      "ordinal": 2,
      "entry_index": 1,
      "kind": "answer",
      "display_text": "Nie pamiętam.",
      "translation_text": "I do not remember.",
      "spoken_text": "Nie pamiętam.",
      "text": "Nie pamiętam.",
      "original_text": "Nie pamiętam.",
      "original_reference_text": "I do not remember.",
      "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "display_answer": "A: Nie pamiętam.",
      "reference_question": "Q: What will you say if you do not remember something?",
      "reference_answer": "A: I do not remember.",
      "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
      "source_answer": "A: Nie pamiętam.",
      "output_file": "audio/0002-entry-0001-answer.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0002-entry-0001-answer.mp3"
    },
    {
      "ordinal": 3,
      "entry_index": 2,
      "kind": "question",
      "display_text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "translation_text": "What will you say when you want to show that it is your opinion?",
      "spoken_text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "original_text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "original_reference_text": "What will you say when you want to show that it is your opinion?",
      "display_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "display_answer": "A: Myślę, że...",
      "reference_question": "Q: What will you say when you want to show that it is your opinion?",
      "reference_answer": "A: I think that...",
      "source_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "source_answer": "A: Myślę, że...",
      "output_file": "audio/0003-entry-0002-question.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0003-entry-0002-question.mp3"
    },
    {
      "ordinal": 4,
      "entry_index": 2,
      "kind": "answer",
      "display_text": "Myślę, że...",
      "translation_text": "I think that...",
      "spoken_text": "Myślę, że...",
      "text": "Myślę, że...",
      "original_text": "Myślę, że...",
      "original_reference_text": "I think that...",
      "display_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "display_answer": "A: Myślę, że...",
      "reference_question": "Q: What will you say when you want to show that it is your opinion?",
      "reference_answer": "A: I think that...",
      "source_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
      "source_answer": "A: Myślę, że...",
      "output_file": "audio/0004-entry-0002-answer.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0004-entry-0002-answer.mp3"
    },
    {
      "ordinal": 5,
      "entry_index": 3,
      "kind": "question",
      "display_text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "translation_text": "What will you say if you want the officer to repeat the question?",
      "spoken_text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "original_text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "original_reference_text": "What will you say if you want the officer to repeat the question?",
      "display_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "display_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
      "reference_question": "Q: What will you say if you want the officer to repeat the question?",
      "reference_answer": "A: Can you please repeat the question?",
      "source_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "source_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
      "output_file": "audio/0005-entry-0003-question.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0005-entry-0003-question.mp3"
    },
    {
      "ordinal": 6,
      "entry_index": 3,
      "kind": "answer",
      "display_text": "Czy może Pan/Pani powtórzyć pytanie?",
      "translation_text": "Can you please repeat the question?",
      "spoken_text": "Czy może Pan/Pani powtórzyć pytanie?",
      "text": "Czy może Pan/Pani powtórzyć pytanie?",
      "original_text": "Czy może Pan/Pani powtórzyć pytanie?",
      "original_reference_text": "Can you please repeat the question?",
      "display_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "display_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
      "reference_question": "Q: What will you say if you want the officer to repeat the question?",
      "reference_answer": "A: Can you please repeat the question?",
      "source_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
      "source_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
      "output_file": "audio/0006-entry-0003-answer.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0006-entry-0003-answer.mp3"
    },
    {
      "ordinal": 7,
      "entry_index": 4,
      "kind": "question",
      "display_text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "translation_text": "What will you say if you do not understand something?",
      "spoken_text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "original_text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "original_reference_text": "What will you say if you do not understand something?",
      "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "display_answer": "A: Nie rozumiem.",
      "reference_question": "Q: What will you say if you do not understand something?",
      "reference_answer": "A: I do not understand.",
      "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "source_answer": "A: Nie rozumiem.",
      "output_file": "audio/0007-entry-0004-question.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0007-entry-0004-question.mp3"
    },
    {
      "ordinal": 8,
      "entry_index": 4,
      "kind": "answer",
      "display_text": "Nie rozumiem.",
      "translation_text": "I do not understand.",
      "spoken_text": "Nie rozumiem.",
      "text": "Nie rozumiem.",
      "original_text": "Nie rozumiem.",
      "original_reference_text": "I do not understand.",
      "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "display_answer": "A: Nie rozumiem.",
      "reference_question": "Q: What will you say if you do not understand something?",
      "reference_answer": "A: I do not understand.",
      "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
      "source_answer": "A: Nie rozumiem.",
      "output_file": "audio/0008-entry-0004-answer.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0008-entry-0004-answer.mp3"
    },
    {
      "ordinal": 9,
      "entry_index": 5,
      "kind": "question",
      "display_text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
      "translation_text": "What will you say if the officer is speaking too quietly?",
      "spoken_text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
      "text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
      "original_text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
      "original_reference_text": "What will you say if the officer is speaking too quietly?",
      "display_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
      "display_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
      "reference_question": "Q: What will you say if the officer is speaking too quietly?",
      "reference_answer": "A: Can you please speak a bit louder?",
      "source_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
      "source_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
      "output_file": "audio/0009-entry-0005-question.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0009-entry-0005-question.mp3"
    },
    {
      "ordinal": 10,
      "entry_index": 5,
      "kind": "answer",
      "display_text": "Czy może Pan/Pani mówić trochę głośniej?",
      "translation_text": "Can you please speak a bit louder?",
      "spoken_text": "Czy może Pan/Pani mówić trochę głośniej?",
      "text": "Czy może Pan/Pani mówić trochę głośniej?",
      "original_text": "Czy może Pan/Pani mówić trochę głośniej?",
      "original_reference_text": "Can you please speak a bit louder?",
      "display_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
      "display_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
      "reference_question": "Q: What will you say if the officer is speaking too quietly?",
      "reference_answer": "A: Can you please speak a bit louder?",
      "source_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
      "source_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
      "output_file": "audio/0010-entry-0005-answer.mp3",
      "output_file_from_repo_root": "output-urzad-basic-pack/audio/0010-entry-0005-answer.mp3"
    }
  ]
};
window.__POLISH_MANIFEST__ = [
  {
    "ordinal": 1,
    "entry_index": 1,
    "kind": "question",
    "display_text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "translation_text": "What will you say if you do not remember something?",
    "spoken_text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "original_text": "Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "original_reference_text": "What will you say if you do not remember something?",
    "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "display_answer": "A: Nie pamiętam.",
    "reference_question": "Q: What will you say if you do not remember something?",
    "reference_answer": "A: I do not remember.",
    "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "source_answer": "A: Nie pamiętam.",
    "output_file": "output-urzad-basic-pack/audio/0001-entry-0001-question.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0001-entry-0001-question.mp3"
  },
  {
    "ordinal": 2,
    "entry_index": 1,
    "kind": "answer",
    "display_text": "Nie pamiętam.",
    "translation_text": "I do not remember.",
    "spoken_text": "Nie pamiętam.",
    "text": "Nie pamiętam.",
    "original_text": "Nie pamiętam.",
    "original_reference_text": "I do not remember.",
    "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "display_answer": "A: Nie pamiętam.",
    "reference_question": "Q: What will you say if you do not remember something?",
    "reference_answer": "A: I do not remember.",
    "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie pamięta?",
    "source_answer": "A: Nie pamiętam.",
    "output_file": "output-urzad-basic-pack/audio/0002-entry-0001-answer.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0002-entry-0001-answer.mp3"
  },
  {
    "ordinal": 3,
    "entry_index": 2,
    "kind": "question",
    "display_text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "translation_text": "What will you say when you want to show that it is your opinion?",
    "spoken_text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "original_text": "Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "original_reference_text": "What will you say when you want to show that it is your opinion?",
    "display_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "display_answer": "A: Myślę, że...",
    "reference_question": "Q: What will you say when you want to show that it is your opinion?",
    "reference_answer": "A: I think that...",
    "source_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "source_answer": "A: Myślę, że...",
    "output_file": "output-urzad-basic-pack/audio/0003-entry-0002-question.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0003-entry-0002-question.mp3"
  },
  {
    "ordinal": 4,
    "entry_index": 2,
    "kind": "answer",
    "display_text": "Myślę, że...",
    "translation_text": "I think that...",
    "spoken_text": "Myślę, że...",
    "text": "Myślę, że...",
    "original_text": "Myślę, że...",
    "original_reference_text": "I think that...",
    "display_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "display_answer": "A: Myślę, że...",
    "reference_question": "Q: What will you say when you want to show that it is your opinion?",
    "reference_answer": "A: I think that...",
    "source_question": "Q: Co Pani powie, kiedy chce Pani zaznaczyć, że to jest Pani opinia?",
    "source_answer": "A: Myślę, że...",
    "output_file": "output-urzad-basic-pack/audio/0004-entry-0002-answer.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0004-entry-0002-answer.mp3"
  },
  {
    "ordinal": 5,
    "entry_index": 3,
    "kind": "question",
    "display_text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "translation_text": "What will you say if you want the officer to repeat the question?",
    "spoken_text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "original_text": "Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "original_reference_text": "What will you say if you want the officer to repeat the question?",
    "display_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "display_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
    "reference_question": "Q: What will you say if you want the officer to repeat the question?",
    "reference_answer": "A: Can you please repeat the question?",
    "source_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "source_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
    "output_file": "output-urzad-basic-pack/audio/0005-entry-0003-question.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0005-entry-0003-question.mp3"
  },
  {
    "ordinal": 6,
    "entry_index": 3,
    "kind": "answer",
    "display_text": "Czy może Pan/Pani powtórzyć pytanie?",
    "translation_text": "Can you please repeat the question?",
    "spoken_text": "Czy może Pan/Pani powtórzyć pytanie?",
    "text": "Czy może Pan/Pani powtórzyć pytanie?",
    "original_text": "Czy może Pan/Pani powtórzyć pytanie?",
    "original_reference_text": "Can you please repeat the question?",
    "display_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "display_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
    "reference_question": "Q: What will you say if you want the officer to repeat the question?",
    "reference_answer": "A: Can you please repeat the question?",
    "source_question": "Q: Co Pani powie, jeśli chce Pani, żeby urzędnik powtórzył pytanie?",
    "source_answer": "A: Czy może Pan/Pani powtórzyć pytanie?",
    "output_file": "output-urzad-basic-pack/audio/0006-entry-0003-answer.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0006-entry-0003-answer.mp3"
  },
  {
    "ordinal": 7,
    "entry_index": 4,
    "kind": "question",
    "display_text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "translation_text": "What will you say if you do not understand something?",
    "spoken_text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "original_text": "Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "original_reference_text": "What will you say if you do not understand something?",
    "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "display_answer": "A: Nie rozumiem.",
    "reference_question": "Q: What will you say if you do not understand something?",
    "reference_answer": "A: I do not understand.",
    "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "source_answer": "A: Nie rozumiem.",
    "output_file": "output-urzad-basic-pack/audio/0007-entry-0004-question.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0007-entry-0004-question.mp3"
  },
  {
    "ordinal": 8,
    "entry_index": 4,
    "kind": "answer",
    "display_text": "Nie rozumiem.",
    "translation_text": "I do not understand.",
    "spoken_text": "Nie rozumiem.",
    "text": "Nie rozumiem.",
    "original_text": "Nie rozumiem.",
    "original_reference_text": "I do not understand.",
    "display_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "display_answer": "A: Nie rozumiem.",
    "reference_question": "Q: What will you say if you do not understand something?",
    "reference_answer": "A: I do not understand.",
    "source_question": "Q: Co Pani powie, jeśli czegoś Pani nie rozumie?",
    "source_answer": "A: Nie rozumiem.",
    "output_file": "output-urzad-basic-pack/audio/0008-entry-0004-answer.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0008-entry-0004-answer.mp3"
  },
  {
    "ordinal": 9,
    "entry_index": 5,
    "kind": "question",
    "display_text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
    "translation_text": "What will you say if the officer is speaking too quietly?",
    "spoken_text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
    "text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
    "original_text": "Co Pani powie, jeśli urzędnik mówi za cicho?",
    "original_reference_text": "What will you say if the officer is speaking too quietly?",
    "display_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
    "display_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
    "reference_question": "Q: What will you say if the officer is speaking too quietly?",
    "reference_answer": "A: Can you please speak a bit louder?",
    "source_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
    "source_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
    "output_file": "output-urzad-basic-pack/audio/0009-entry-0005-question.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0009-entry-0005-question.mp3"
  },
  {
    "ordinal": 10,
    "entry_index": 5,
    "kind": "answer",
    "display_text": "Czy może Pan/Pani mówić trochę głośniej?",
    "translation_text": "Can you please speak a bit louder?",
    "spoken_text": "Czy może Pan/Pani mówić trochę głośniej?",
    "text": "Czy może Pan/Pani mówić trochę głośniej?",
    "original_text": "Czy może Pan/Pani mówić trochę głośniej?",
    "original_reference_text": "Can you please speak a bit louder?",
    "display_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
    "display_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
    "reference_question": "Q: What will you say if the officer is speaking too quietly?",
    "reference_answer": "A: Can you please speak a bit louder?",
    "source_question": "Q: Co Pani powie, jeśli urzędnik mówi za cicho?",
    "source_answer": "A: Czy może Pan/Pani mówić trochę głośniej?",
    "output_file": "output-urzad-basic-pack/audio/0010-entry-0005-answer.mp3",
    "output_file_from_repo_root": "output-urzad-basic-pack/audio/0010-entry-0005-answer.mp3"
  }
];
