window.__LANGUAGE_LEARNING_BUNDLE__ = {
  "meta": {
    "schema_version": "2.0",
    "generated_at": "2026-07-16T22:46:32.547863+00:00",
    "input_file": "content/urzad-polish-culture-qa.txt",
    "study_column": 0,
    "reference_column": 1,
    "mode": "both",
    "voice": "pl-PL-ZofiaNeural",
    "study_language_name": "Polish",
    "reference_language_name": "English",
    "dashboard_title": "Urząd Poland Knowledge Practice",
    "dashboard_subtitle": "Practice Poland knowledge, traditions, holidays, translations, and Polish audio.",
    "output_dir_name": "output-urzad-culture-pack",
    "profile_file": null,
    "pronunciation_file": null,
    "entry_count": 17,
    "item_count": 34
  },
  "items": [
    {
      "ordinal": 1,
      "entry_index": 1,
      "kind": "question",
      "display_text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "translation_text": "What is the area around your apartment like? What is nearby where you live?",
      "spoken_text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "original_text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "original_reference_text": "What is the area around your apartment like? What is nearby where you live?",
      "display_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "display_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "reference_question": "Q: What is the area around your apartment like? What is nearby where you live?",
      "reference_answer": "A: I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
      "source_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "source_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "output_file": "audio/0001-entry-0001-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0001-entry-0001-question.mp3"
    },
    {
      "ordinal": 2,
      "entry_index": 1,
      "kind": "answer",
      "display_text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "translation_text": "I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
      "spoken_text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "original_text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "original_reference_text": "I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
      "display_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "display_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "reference_question": "Q: What is the area around your apartment like? What is nearby where you live?",
      "reference_answer": "A: I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
      "source_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
      "source_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
      "output_file": "audio/0002-entry-0001-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0002-entry-0001-answer.mp3"
    },
    {
      "ordinal": 3,
      "entry_index": 2,
      "kind": "question",
      "display_text": "Co wiesz o Polsce?",
      "translation_text": "What do you know about Poland?",
      "spoken_text": "Co wiesz o Polsce?",
      "text": "Co wiesz o Polsce?",
      "original_text": "Co wiesz o Polsce?",
      "original_reference_text": "What do you know about Poland?",
      "display_question": "Q: Co wiesz o Polsce?",
      "display_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "reference_question": "Q: What do you know about Poland?",
      "reference_answer": "A: The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
      "source_question": "Q: Co wiesz o Polsce?",
      "source_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "output_file": "audio/0003-entry-0002-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0003-entry-0002-question.mp3"
    },
    {
      "ordinal": 4,
      "entry_index": 2,
      "kind": "answer",
      "display_text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "translation_text": "The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
      "spoken_text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "original_text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "original_reference_text": "The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
      "display_question": "Q: Co wiesz o Polsce?",
      "display_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "reference_question": "Q: What do you know about Poland?",
      "reference_answer": "A: The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
      "source_question": "Q: Co wiesz o Polsce?",
      "source_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
      "output_file": "audio/0004-entry-0002-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0004-entry-0002-answer.mp3"
    },
    {
      "ordinal": 5,
      "entry_index": 3,
      "kind": "question",
      "display_text": "Jakie znasz polskie święta narodowe?",
      "translation_text": "Which Polish national holidays do you know?",
      "spoken_text": "Jakie znasz polskie święta narodowe?",
      "text": "Jakie znasz polskie święta narodowe?",
      "original_text": "Jakie znasz polskie święta narodowe?",
      "original_reference_text": "Which Polish national holidays do you know?",
      "display_question": "Q: Jakie znasz polskie święta narodowe?",
      "display_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "reference_question": "Q: Which Polish national holidays do you know?",
      "reference_answer": "A: Independence Day — November 11. Constitution Day — May 3.",
      "source_question": "Q: Jakie znasz polskie święta narodowe?",
      "source_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "output_file": "audio/0005-entry-0003-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0005-entry-0003-question.mp3"
    },
    {
      "ordinal": 6,
      "entry_index": 3,
      "kind": "answer",
      "display_text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "translation_text": "Independence Day — November 11. Constitution Day — May 3.",
      "spoken_text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "original_text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "original_reference_text": "Independence Day — November 11. Constitution Day — May 3.",
      "display_question": "Q: Jakie znasz polskie święta narodowe?",
      "display_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "reference_question": "Q: Which Polish national holidays do you know?",
      "reference_answer": "A: Independence Day — November 11. Constitution Day — May 3.",
      "source_question": "Q: Jakie znasz polskie święta narodowe?",
      "source_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
      "output_file": "audio/0006-entry-0003-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0006-entry-0003-answer.mp3"
    },
    {
      "ordinal": 7,
      "entry_index": 4,
      "kind": "question",
      "display_text": "Jakie znasz polskie święta religijne?",
      "translation_text": "Which Polish religious holidays do you know?",
      "spoken_text": "Jakie znasz polskie święta religijne?",
      "text": "Jakie znasz polskie święta religijne?",
      "original_text": "Jakie znasz polskie święta religijne?",
      "original_reference_text": "Which Polish religious holidays do you know?",
      "display_question": "Q: Jakie znasz polskie święta religijne?",
      "display_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "reference_question": "Q: Which Polish religious holidays do you know?",
      "reference_answer": "A: Easter, Christmas, All Saints’ Day — November 1.",
      "source_question": "Q: Jakie znasz polskie święta religijne?",
      "source_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "output_file": "audio/0007-entry-0004-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0007-entry-0004-question.mp3"
    },
    {
      "ordinal": 8,
      "entry_index": 4,
      "kind": "answer",
      "display_text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "translation_text": "Easter, Christmas, All Saints’ Day — November 1.",
      "spoken_text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "original_text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "original_reference_text": "Easter, Christmas, All Saints’ Day — November 1.",
      "display_question": "Q: Jakie znasz polskie święta religijne?",
      "display_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "reference_question": "Q: Which Polish religious holidays do you know?",
      "reference_answer": "A: Easter, Christmas, All Saints’ Day — November 1.",
      "source_question": "Q: Jakie znasz polskie święta religijne?",
      "source_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
      "output_file": "audio/0008-entry-0004-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0008-entry-0004-answer.mp3"
    },
    {
      "ordinal": 9,
      "entry_index": 5,
      "kind": "question",
      "display_text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "translation_text": "What is Christmas Eve dinner and when do we celebrate it in Poland?",
      "spoken_text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "original_text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "original_reference_text": "What is Christmas Eve dinner and when do we celebrate it in Poland?",
      "display_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "display_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "reference_question": "Q: What is Christmas Eve dinner and when do we celebrate it in Poland?",
      "reference_answer": "A: It is a special dinner that we celebrate on December 24.",
      "source_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "source_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "output_file": "audio/0009-entry-0005-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0009-entry-0005-question.mp3"
    },
    {
      "ordinal": 10,
      "entry_index": 5,
      "kind": "answer",
      "display_text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "translation_text": "It is a special dinner that we celebrate on December 24.",
      "spoken_text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "original_text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "original_reference_text": "It is a special dinner that we celebrate on December 24.",
      "display_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "display_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "reference_question": "Q: What is Christmas Eve dinner and when do we celebrate it in Poland?",
      "reference_answer": "A: It is a special dinner that we celebrate on December 24.",
      "source_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
      "source_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
      "output_file": "audio/0010-entry-0005-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0010-entry-0005-answer.mp3"
    },
    {
      "ordinal": 11,
      "entry_index": 6,
      "kind": "question",
      "display_text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
      "translation_text": "Which three Christmas traditions do you know?",
      "spoken_text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
      "text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
      "original_text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
      "original_reference_text": "Which three Christmas traditions do you know?",
      "display_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
      "display_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "reference_question": "Q: Which three Christmas traditions do you know?",
      "reference_answer": "A: We decorate the Christmas tree, give presents, and share the Christmas wafer.",
      "source_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
      "source_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "output_file": "audio/0011-entry-0006-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0011-entry-0006-question.mp3"
    },
    {
      "ordinal": 12,
      "entry_index": 6,
      "kind": "answer",
      "display_text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "translation_text": "We decorate the Christmas tree, give presents, and share the Christmas wafer.",
      "spoken_text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "original_text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "original_reference_text": "We decorate the Christmas tree, give presents, and share the Christmas wafer.",
      "display_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
      "display_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "reference_question": "Q: Which three Christmas traditions do you know?",
      "reference_answer": "A: We decorate the Christmas tree, give presents, and share the Christmas wafer.",
      "source_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
      "source_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
      "output_file": "audio/0012-entry-0006-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0012-entry-0006-answer.mp3"
    },
    {
      "ordinal": 13,
      "entry_index": 7,
      "kind": "question",
      "display_text": "Kiedy obchodzimy w Polsce Wielkanoc?",
      "translation_text": "When do we celebrate Easter in Poland?",
      "spoken_text": "Kiedy obchodzimy w Polsce Wielkanoc?",
      "text": "Kiedy obchodzimy w Polsce Wielkanoc?",
      "original_text": "Kiedy obchodzimy w Polsce Wielkanoc?",
      "original_reference_text": "When do we celebrate Easter in Poland?",
      "display_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
      "display_answer": "A: W marcu albo w kwietniu.",
      "reference_question": "Q: When do we celebrate Easter in Poland?",
      "reference_answer": "A: In March or in April.",
      "source_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
      "source_answer": "A: W marcu albo w kwietniu.",
      "output_file": "audio/0013-entry-0007-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0013-entry-0007-question.mp3"
    },
    {
      "ordinal": 14,
      "entry_index": 7,
      "kind": "answer",
      "display_text": "W marcu albo w kwietniu.",
      "translation_text": "In March or in April.",
      "spoken_text": "W marcu albo w kwietniu.",
      "text": "W marcu albo w kwietniu.",
      "original_text": "W marcu albo w kwietniu.",
      "original_reference_text": "In March or in April.",
      "display_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
      "display_answer": "A: W marcu albo w kwietniu.",
      "reference_question": "Q: When do we celebrate Easter in Poland?",
      "reference_answer": "A: In March or in April.",
      "source_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
      "source_answer": "A: W marcu albo w kwietniu.",
      "output_file": "audio/0014-entry-0007-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0014-entry-0007-answer.mp3"
    },
    {
      "ordinal": 15,
      "entry_index": 8,
      "kind": "question",
      "display_text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "translation_text": "The egg is a symbol of which Polish religious holiday? What do we do?",
      "spoken_text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "original_text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "original_reference_text": "The egg is a symbol of which Polish religious holiday? What do we do?",
      "display_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "display_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "reference_question": "Q: The egg is a symbol of which Polish religious holiday? What do we do?",
      "reference_answer": "A: It is a symbol of Easter. Polish people paint eggs then.",
      "source_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "source_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "output_file": "audio/0015-entry-0008-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0015-entry-0008-question.mp3"
    },
    {
      "ordinal": 16,
      "entry_index": 8,
      "kind": "answer",
      "display_text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "translation_text": "It is a symbol of Easter. Polish people paint eggs then.",
      "spoken_text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "original_text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "original_reference_text": "It is a symbol of Easter. Polish people paint eggs then.",
      "display_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "display_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "reference_question": "Q: The egg is a symbol of which Polish religious holiday? What do we do?",
      "reference_answer": "A: It is a symbol of Easter. Polish people paint eggs then.",
      "source_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
      "source_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
      "output_file": "audio/0016-entry-0008-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0016-entry-0008-answer.mp3"
    },
    {
      "ordinal": 17,
      "entry_index": 9,
      "kind": "question",
      "display_text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "translation_text": "When do Polish people visit cemeteries? Do you know which holiday it is?",
      "spoken_text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "original_text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "original_reference_text": "When do Polish people visit cemeteries? Do you know which holiday it is?",
      "display_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "display_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
      "reference_question": "Q: When do Polish people visit cemeteries? Do you know which holiday it is?",
      "reference_answer": "A: On All Saints’ Day, November 1.",
      "source_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "source_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
      "output_file": "audio/0017-entry-0009-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0017-entry-0009-question.mp3"
    },
    {
      "ordinal": 18,
      "entry_index": 9,
      "kind": "answer",
      "display_text": "W Dzień Wszystkich Świętych, 1 listopada.",
      "translation_text": "On All Saints’ Day, November 1.",
      "spoken_text": "W Dzień Wszystkich Świętych, 1 listopada.",
      "text": "W Dzień Wszystkich Świętych, 1 listopada.",
      "original_text": "W Dzień Wszystkich Świętych, 1 listopada.",
      "original_reference_text": "On All Saints’ Day, November 1.",
      "display_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "display_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
      "reference_question": "Q: When do Polish people visit cemeteries? Do you know which holiday it is?",
      "reference_answer": "A: On All Saints’ Day, November 1.",
      "source_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
      "source_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
      "output_file": "audio/0018-entry-0009-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0018-entry-0009-answer.mp3"
    },
    {
      "ordinal": 19,
      "entry_index": 10,
      "kind": "question",
      "display_text": "Co to są imieniny?",
      "translation_text": "What is a name day?",
      "spoken_text": "Co to są imieniny?",
      "text": "Co to są imieniny?",
      "original_text": "Co to są imieniny?",
      "original_reference_text": "What is a name day?",
      "display_question": "Q: Co to są imieniny?",
      "display_answer": "A: To dzień twojego imienia.",
      "reference_question": "Q: What is a name day?",
      "reference_answer": "A: It is the day of your given name.",
      "source_question": "Q: Co to są imieniny?",
      "source_answer": "A: To dzień twojego imienia.",
      "output_file": "audio/0019-entry-0010-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0019-entry-0010-question.mp3"
    },
    {
      "ordinal": 20,
      "entry_index": 10,
      "kind": "answer",
      "display_text": "To dzień twojego imienia.",
      "translation_text": "It is the day of your given name.",
      "spoken_text": "To dzień twojego imienia.",
      "text": "To dzień twojego imienia.",
      "original_text": "To dzień twojego imienia.",
      "original_reference_text": "It is the day of your given name.",
      "display_question": "Q: Co to są imieniny?",
      "display_answer": "A: To dzień twojego imienia.",
      "reference_question": "Q: What is a name day?",
      "reference_answer": "A: It is the day of your given name.",
      "source_question": "Q: Co to są imieniny?",
      "source_answer": "A: To dzień twojego imienia.",
      "output_file": "audio/0020-entry-0010-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0020-entry-0010-answer.mp3"
    },
    {
      "ordinal": 21,
      "entry_index": 11,
      "kind": "question",
      "display_text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "translation_text": "Do you know which song Polish people sing for birthdays?",
      "spoken_text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "original_text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "original_reference_text": "Do you know which song Polish people sing for birthdays?",
      "display_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "display_answer": "A: Sto lat, sto lat.",
      "reference_question": "Q: Do you know which song Polish people sing for birthdays?",
      "reference_answer": "A: “Sto lat, sto lat.”",
      "source_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "source_answer": "A: Sto lat, sto lat.",
      "output_file": "audio/0021-entry-0011-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0021-entry-0011-question.mp3"
    },
    {
      "ordinal": 22,
      "entry_index": 11,
      "kind": "answer",
      "display_text": "Sto lat, sto lat.",
      "translation_text": "“Sto lat, sto lat.”",
      "spoken_text": "Sto lat, sto lat.",
      "text": "Sto lat, sto lat.",
      "original_text": "Sto lat, sto lat.",
      "original_reference_text": "“Sto lat, sto lat.”",
      "display_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "display_answer": "A: Sto lat, sto lat.",
      "reference_question": "Q: Do you know which song Polish people sing for birthdays?",
      "reference_answer": "A: “Sto lat, sto lat.”",
      "source_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
      "source_answer": "A: Sto lat, sto lat.",
      "output_file": "audio/0022-entry-0011-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0022-entry-0011-answer.mp3"
    },
    {
      "ordinal": 23,
      "entry_index": 12,
      "kind": "question",
      "display_text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "translation_text": "What is your favorite Polish holiday or tradition? Why?",
      "spoken_text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "original_text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "original_reference_text": "What is your favorite Polish holiday or tradition? Why?",
      "display_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "display_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "reference_question": "Q: What is your favorite Polish holiday or tradition? Why?",
      "reference_answer": "A: My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
      "source_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "source_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "output_file": "audio/0023-entry-0012-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0023-entry-0012-question.mp3"
    },
    {
      "ordinal": 24,
      "entry_index": 12,
      "kind": "answer",
      "display_text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "translation_text": "My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
      "spoken_text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "original_text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "original_reference_text": "My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
      "display_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "display_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "reference_question": "Q: What is your favorite Polish holiday or tradition? Why?",
      "reference_answer": "A: My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
      "source_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
      "source_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
      "output_file": "audio/0024-entry-0012-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0024-entry-0012-answer.mp3"
    },
    {
      "ordinal": 25,
      "entry_index": 13,
      "kind": "question",
      "display_text": "Czy lubi Pani Zakopane?",
      "translation_text": "Do you like Zakopane?",
      "spoken_text": "Czy lubi Pani Zakopane?",
      "text": "Czy lubi Pani Zakopane?",
      "original_text": "Czy lubi Pani Zakopane?",
      "original_reference_text": "Do you like Zakopane?",
      "display_question": "Q: Czy lubi Pani Zakopane?",
      "display_answer": "A: Tak, bardzo lubię Zakopane.",
      "reference_question": "Q: Do you like Zakopane?",
      "reference_answer": "A: Yes, I like Zakopane very much.",
      "source_question": "Q: Czy lubi Pani Zakopane?",
      "source_answer": "A: Tak, bardzo lubię Zakopane.",
      "output_file": "audio/0025-entry-0013-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0025-entry-0013-question.mp3"
    },
    {
      "ordinal": 26,
      "entry_index": 13,
      "kind": "answer",
      "display_text": "Tak, bardzo lubię Zakopane.",
      "translation_text": "Yes, I like Zakopane very much.",
      "spoken_text": "Tak, bardzo lubię Zakopane.",
      "text": "Tak, bardzo lubię Zakopane.",
      "original_text": "Tak, bardzo lubię Zakopane.",
      "original_reference_text": "Yes, I like Zakopane very much.",
      "display_question": "Q: Czy lubi Pani Zakopane?",
      "display_answer": "A: Tak, bardzo lubię Zakopane.",
      "reference_question": "Q: Do you like Zakopane?",
      "reference_answer": "A: Yes, I like Zakopane very much.",
      "source_question": "Q: Czy lubi Pani Zakopane?",
      "source_answer": "A: Tak, bardzo lubię Zakopane.",
      "output_file": "audio/0026-entry-0013-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0026-entry-0013-answer.mp3"
    },
    {
      "ordinal": 27,
      "entry_index": 14,
      "kind": "question",
      "display_text": "Jak często jeździ Pani do Zakopanego?",
      "translation_text": "How often do you go to Zakopane?",
      "spoken_text": "Jak często jeździ Pani do Zakopanego?",
      "text": "Jak często jeździ Pani do Zakopanego?",
      "original_text": "Jak często jeździ Pani do Zakopanego?",
      "original_reference_text": "How often do you go to Zakopane?",
      "display_question": "Q: Jak często jeździ Pani do Zakopanego?",
      "display_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "reference_question": "Q: How often do you go to Zakopane?",
      "reference_answer": "A: We go to Zakopane two or three times a year.",
      "source_question": "Q: Jak często jeździ Pani do Zakopanego?",
      "source_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "output_file": "audio/0027-entry-0014-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0027-entry-0014-question.mp3"
    },
    {
      "ordinal": 28,
      "entry_index": 14,
      "kind": "answer",
      "display_text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "translation_text": "We go to Zakopane two or three times a year.",
      "spoken_text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "original_text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "original_reference_text": "We go to Zakopane two or three times a year.",
      "display_question": "Q: Jak często jeździ Pani do Zakopanego?",
      "display_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "reference_question": "Q: How often do you go to Zakopane?",
      "reference_answer": "A: We go to Zakopane two or three times a year.",
      "source_question": "Q: Jak często jeździ Pani do Zakopanego?",
      "source_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
      "output_file": "audio/0028-entry-0014-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0028-entry-0014-answer.mp3"
    },
    {
      "ordinal": 29,
      "entry_index": 15,
      "kind": "question",
      "display_text": "Co Pani myśli o Krakowie i Małopolsce?",
      "translation_text": "What do you think about Kraków and Małopolska?",
      "spoken_text": "Co Pani myśli o Krakowie i Małopolsce?",
      "text": "Co Pani myśli o Krakowie i Małopolsce?",
      "original_text": "Co Pani myśli o Krakowie i Małopolsce?",
      "original_reference_text": "What do you think about Kraków and Małopolska?",
      "display_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
      "display_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "reference_question": "Q: What do you think about Kraków and Małopolska?",
      "reference_answer": "A: Kraków is very green, and Małopolska is also very green and beautiful.",
      "source_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
      "source_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "output_file": "audio/0029-entry-0015-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0029-entry-0015-question.mp3"
    },
    {
      "ordinal": 30,
      "entry_index": 15,
      "kind": "answer",
      "display_text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "translation_text": "Kraków is very green, and Małopolska is also very green and beautiful.",
      "spoken_text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "original_text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "original_reference_text": "Kraków is very green, and Małopolska is also very green and beautiful.",
      "display_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
      "display_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "reference_question": "Q: What do you think about Kraków and Małopolska?",
      "reference_answer": "A: Kraków is very green, and Małopolska is also very green and beautiful.",
      "source_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
      "source_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
      "output_file": "audio/0030-entry-0015-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0030-entry-0015-answer.mp3"
    },
    {
      "ordinal": 31,
      "entry_index": 16,
      "kind": "question",
      "display_text": "Jakie góry w Małopolsce Pani lubi?",
      "translation_text": "Which mountains in Małopolska do you like?",
      "spoken_text": "Jakie góry w Małopolsce Pani lubi?",
      "text": "Jakie góry w Małopolsce Pani lubi?",
      "original_text": "Jakie góry w Małopolsce Pani lubi?",
      "original_reference_text": "Which mountains in Małopolska do you like?",
      "display_question": "Q: Jakie góry w Małopolsce Pani lubi?",
      "display_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "reference_question": "Q: Which mountains in Małopolska do you like?",
      "reference_answer": "A: I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
      "source_question": "Q: Jakie góry w Małopolsce Pani lubi?",
      "source_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "output_file": "audio/0031-entry-0016-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0031-entry-0016-question.mp3"
    },
    {
      "ordinal": 32,
      "entry_index": 16,
      "kind": "answer",
      "display_text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "translation_text": "I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
      "spoken_text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "original_text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "original_reference_text": "I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
      "display_question": "Q: Jakie góry w Małopolsce Pani lubi?",
      "display_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "reference_question": "Q: Which mountains in Małopolska do you like?",
      "reference_answer": "A: I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
      "source_question": "Q: Jakie góry w Małopolsce Pani lubi?",
      "source_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
      "output_file": "audio/0032-entry-0016-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0032-entry-0016-answer.mp3"
    },
    {
      "ordinal": 33,
      "entry_index": 17,
      "kind": "question",
      "display_text": "Dlaczego lubi Pani Kraków albo Polskę?",
      "translation_text": "Why do you like Kraków or Poland?",
      "spoken_text": "Dlaczego lubi Pani Kraków albo Polskę?",
      "text": "Dlaczego lubi Pani Kraków albo Polskę?",
      "original_text": "Dlaczego lubi Pani Kraków albo Polskę?",
      "original_reference_text": "Why do you like Kraków or Poland?",
      "display_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
      "display_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "reference_question": "Q: Why do you like Kraków or Poland?",
      "reference_answer": "A: Kraków is very beautiful in winter as well. The snow is very beautiful.",
      "source_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
      "source_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "output_file": "audio/0033-entry-0017-question.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0033-entry-0017-question.mp3"
    },
    {
      "ordinal": 34,
      "entry_index": 17,
      "kind": "answer",
      "display_text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "translation_text": "Kraków is very beautiful in winter as well. The snow is very beautiful.",
      "spoken_text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "original_text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "original_reference_text": "Kraków is very beautiful in winter as well. The snow is very beautiful.",
      "display_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
      "display_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "reference_question": "Q: Why do you like Kraków or Poland?",
      "reference_answer": "A: Kraków is very beautiful in winter as well. The snow is very beautiful.",
      "source_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
      "source_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
      "output_file": "audio/0034-entry-0017-answer.mp3",
      "output_file_from_repo_root": "output-urzad-culture-pack/audio/0034-entry-0017-answer.mp3"
    }
  ]
};
window.__POLISH_MANIFEST__ = [
  {
    "ordinal": 1,
    "entry_index": 1,
    "kind": "question",
    "display_text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "translation_text": "What is the area around your apartment like? What is nearby where you live?",
    "spoken_text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "original_text": "Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "original_reference_text": "What is the area around your apartment like? What is nearby where you live?",
    "display_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "display_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "reference_question": "Q: What is the area around your apartment like? What is nearby where you live?",
    "reference_answer": "A: I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
    "source_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "source_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "output_file": "output-urzad-culture-pack/audio/0001-entry-0001-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0001-entry-0001-question.mp3"
  },
  {
    "ordinal": 2,
    "entry_index": 1,
    "kind": "answer",
    "display_text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "translation_text": "I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
    "spoken_text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "original_text": "Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "original_reference_text": "I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
    "display_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "display_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "reference_question": "Q: What is the area around your apartment like? What is nearby where you live?",
    "reference_answer": "A: I live in Kraków in the Bonarka area. There is a lot of greenery and a park. It is a very nice place. Near my apartment there is Bonarka City Center. I also have Lidl, Biedronka, a pharmacy, a school, and a kindergarten nearby. There is good bus and tram transport.",
    "source_question": "Q: Jakie jest otoczenie pani mieszkania? Co jest w okolicy, gdzie pani mieszka?",
    "source_answer": "A: Mieszkam w Krakowie w okolicy Bonarki. Jest dużo zieleni i park. To miejsce jest bardzo ładne. Blisko mojego mieszkania jest centrum handlowe Bonarka City Center. Blisko mam też Lidl, Biedronkę, aptekę, szkołę i przedszkole. Jest dobra komunikacja autobusowa i tramwajowa.",
    "output_file": "output-urzad-culture-pack/audio/0002-entry-0001-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0002-entry-0001-answer.mp3"
  },
  {
    "ordinal": 3,
    "entry_index": 2,
    "kind": "question",
    "display_text": "Co wiesz o Polsce?",
    "translation_text": "What do you know about Poland?",
    "spoken_text": "Co wiesz o Polsce?",
    "text": "Co wiesz o Polsce?",
    "original_text": "Co wiesz o Polsce?",
    "original_reference_text": "What do you know about Poland?",
    "display_question": "Q: Co wiesz o Polsce?",
    "display_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "reference_question": "Q: What do you know about Poland?",
    "reference_answer": "A: The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
    "source_question": "Q: Co wiesz o Polsce?",
    "source_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "output_file": "output-urzad-culture-pack/audio/0003-entry-0002-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0003-entry-0002-question.mp3"
  },
  {
    "ordinal": 4,
    "entry_index": 2,
    "kind": "answer",
    "display_text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "translation_text": "The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
    "spoken_text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "original_text": "Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "original_reference_text": "The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
    "display_question": "Q: Co wiesz o Polsce?",
    "display_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "reference_question": "Q: What do you know about Poland?",
    "reference_answer": "A: The full name of Poland is the Republic of Poland. Poland’s national symbols are: the coat of arms — the white eagle, the flag — white and red, and the Polish anthem. Poland is a democracy. The president is the most important state authority in Poland. Polish people speak Polish. The capital of Poland is Warsaw. Cities in Poland include Warsaw, Kraków, Wrocław, and Lublin. The highest mountains in Poland are the Tatra Mountains. Poland’s sea is the Baltic Sea. Poland’s neighbors are Germany, the Czech Republic, Ukraine, Belarus, Lithuania, and Russia.",
    "source_question": "Q: Co wiesz o Polsce?",
    "source_answer": "A: Pełna nazwa Polski to Rzeczpospolita Polska. Symbole narodowe Polski to: godło — orzeł biały, flaga — biało-czerwona, hymn polski. W Polsce jest demokracja. Najważniejszy w Polsce jest prezydent. Polacy mówią po polsku. Stolicą Polski jest Warszawa. Miasta w Polsce to: Warszawa, Kraków, Wrocław, Lublin. Najwyższe góry w Polsce to Tatry. Polskie morze to Bałtyk. Polska ma sąsiadów: Niemcy, Czechy, Ukraina, Białoruś, Litwa, Rosja.",
    "output_file": "output-urzad-culture-pack/audio/0004-entry-0002-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0004-entry-0002-answer.mp3"
  },
  {
    "ordinal": 5,
    "entry_index": 3,
    "kind": "question",
    "display_text": "Jakie znasz polskie święta narodowe?",
    "translation_text": "Which Polish national holidays do you know?",
    "spoken_text": "Jakie znasz polskie święta narodowe?",
    "text": "Jakie znasz polskie święta narodowe?",
    "original_text": "Jakie znasz polskie święta narodowe?",
    "original_reference_text": "Which Polish national holidays do you know?",
    "display_question": "Q: Jakie znasz polskie święta narodowe?",
    "display_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "reference_question": "Q: Which Polish national holidays do you know?",
    "reference_answer": "A: Independence Day — November 11. Constitution Day — May 3.",
    "source_question": "Q: Jakie znasz polskie święta narodowe?",
    "source_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "output_file": "output-urzad-culture-pack/audio/0005-entry-0003-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0005-entry-0003-question.mp3"
  },
  {
    "ordinal": 6,
    "entry_index": 3,
    "kind": "answer",
    "display_text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "translation_text": "Independence Day — November 11. Constitution Day — May 3.",
    "spoken_text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "original_text": "Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "original_reference_text": "Independence Day — November 11. Constitution Day — May 3.",
    "display_question": "Q: Jakie znasz polskie święta narodowe?",
    "display_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "reference_question": "Q: Which Polish national holidays do you know?",
    "reference_answer": "A: Independence Day — November 11. Constitution Day — May 3.",
    "source_question": "Q: Jakie znasz polskie święta narodowe?",
    "source_answer": "A: Dzień Niepodległości — 11 listopada. Dzień Konstytucji 3 Maja.",
    "output_file": "output-urzad-culture-pack/audio/0006-entry-0003-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0006-entry-0003-answer.mp3"
  },
  {
    "ordinal": 7,
    "entry_index": 4,
    "kind": "question",
    "display_text": "Jakie znasz polskie święta religijne?",
    "translation_text": "Which Polish religious holidays do you know?",
    "spoken_text": "Jakie znasz polskie święta religijne?",
    "text": "Jakie znasz polskie święta religijne?",
    "original_text": "Jakie znasz polskie święta religijne?",
    "original_reference_text": "Which Polish religious holidays do you know?",
    "display_question": "Q: Jakie znasz polskie święta religijne?",
    "display_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "reference_question": "Q: Which Polish religious holidays do you know?",
    "reference_answer": "A: Easter, Christmas, All Saints’ Day — November 1.",
    "source_question": "Q: Jakie znasz polskie święta religijne?",
    "source_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "output_file": "output-urzad-culture-pack/audio/0007-entry-0004-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0007-entry-0004-question.mp3"
  },
  {
    "ordinal": 8,
    "entry_index": 4,
    "kind": "answer",
    "display_text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "translation_text": "Easter, Christmas, All Saints’ Day — November 1.",
    "spoken_text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "original_text": "Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "original_reference_text": "Easter, Christmas, All Saints’ Day — November 1.",
    "display_question": "Q: Jakie znasz polskie święta religijne?",
    "display_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "reference_question": "Q: Which Polish religious holidays do you know?",
    "reference_answer": "A: Easter, Christmas, All Saints’ Day — November 1.",
    "source_question": "Q: Jakie znasz polskie święta religijne?",
    "source_answer": "A: Wielkanoc, Boże Narodzenie, Dzień Wszystkich Świętych — 1 listopada.",
    "output_file": "output-urzad-culture-pack/audio/0008-entry-0004-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0008-entry-0004-answer.mp3"
  },
  {
    "ordinal": 9,
    "entry_index": 5,
    "kind": "question",
    "display_text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "translation_text": "What is Christmas Eve dinner and when do we celebrate it in Poland?",
    "spoken_text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "original_text": "Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "original_reference_text": "What is Christmas Eve dinner and when do we celebrate it in Poland?",
    "display_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "display_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "reference_question": "Q: What is Christmas Eve dinner and when do we celebrate it in Poland?",
    "reference_answer": "A: It is a special dinner that we celebrate on December 24.",
    "source_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "source_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "output_file": "output-urzad-culture-pack/audio/0009-entry-0005-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0009-entry-0005-question.mp3"
  },
  {
    "ordinal": 10,
    "entry_index": 5,
    "kind": "answer",
    "display_text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "translation_text": "It is a special dinner that we celebrate on December 24.",
    "spoken_text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "original_text": "To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "original_reference_text": "It is a special dinner that we celebrate on December 24.",
    "display_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "display_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "reference_question": "Q: What is Christmas Eve dinner and when do we celebrate it in Poland?",
    "reference_answer": "A: It is a special dinner that we celebrate on December 24.",
    "source_question": "Q: Co to jest Wigilia i kiedy ją obchodzimy w Polsce?",
    "source_answer": "A: To jest specjalna kolacja, którą obchodzimy 24 grudnia.",
    "output_file": "output-urzad-culture-pack/audio/0010-entry-0005-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0010-entry-0005-answer.mp3"
  },
  {
    "ordinal": 11,
    "entry_index": 6,
    "kind": "question",
    "display_text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
    "translation_text": "Which three Christmas traditions do you know?",
    "spoken_text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
    "text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
    "original_text": "Jakie znasz 3 tradycje Bożego Narodzenia?",
    "original_reference_text": "Which three Christmas traditions do you know?",
    "display_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
    "display_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "reference_question": "Q: Which three Christmas traditions do you know?",
    "reference_answer": "A: We decorate the Christmas tree, give presents, and share the Christmas wafer.",
    "source_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
    "source_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "output_file": "output-urzad-culture-pack/audio/0011-entry-0006-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0011-entry-0006-question.mp3"
  },
  {
    "ordinal": 12,
    "entry_index": 6,
    "kind": "answer",
    "display_text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "translation_text": "We decorate the Christmas tree, give presents, and share the Christmas wafer.",
    "spoken_text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "original_text": "Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "original_reference_text": "We decorate the Christmas tree, give presents, and share the Christmas wafer.",
    "display_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
    "display_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "reference_question": "Q: Which three Christmas traditions do you know?",
    "reference_answer": "A: We decorate the Christmas tree, give presents, and share the Christmas wafer.",
    "source_question": "Q: Jakie znasz 3 tradycje Bożego Narodzenia?",
    "source_answer": "A: Dekorujemy choinkę, dajemy prezenty i dzielimy się opłatkiem.",
    "output_file": "output-urzad-culture-pack/audio/0012-entry-0006-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0012-entry-0006-answer.mp3"
  },
  {
    "ordinal": 13,
    "entry_index": 7,
    "kind": "question",
    "display_text": "Kiedy obchodzimy w Polsce Wielkanoc?",
    "translation_text": "When do we celebrate Easter in Poland?",
    "spoken_text": "Kiedy obchodzimy w Polsce Wielkanoc?",
    "text": "Kiedy obchodzimy w Polsce Wielkanoc?",
    "original_text": "Kiedy obchodzimy w Polsce Wielkanoc?",
    "original_reference_text": "When do we celebrate Easter in Poland?",
    "display_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
    "display_answer": "A: W marcu albo w kwietniu.",
    "reference_question": "Q: When do we celebrate Easter in Poland?",
    "reference_answer": "A: In March or in April.",
    "source_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
    "source_answer": "A: W marcu albo w kwietniu.",
    "output_file": "output-urzad-culture-pack/audio/0013-entry-0007-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0013-entry-0007-question.mp3"
  },
  {
    "ordinal": 14,
    "entry_index": 7,
    "kind": "answer",
    "display_text": "W marcu albo w kwietniu.",
    "translation_text": "In March or in April.",
    "spoken_text": "W marcu albo w kwietniu.",
    "text": "W marcu albo w kwietniu.",
    "original_text": "W marcu albo w kwietniu.",
    "original_reference_text": "In March or in April.",
    "display_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
    "display_answer": "A: W marcu albo w kwietniu.",
    "reference_question": "Q: When do we celebrate Easter in Poland?",
    "reference_answer": "A: In March or in April.",
    "source_question": "Q: Kiedy obchodzimy w Polsce Wielkanoc?",
    "source_answer": "A: W marcu albo w kwietniu.",
    "output_file": "output-urzad-culture-pack/audio/0014-entry-0007-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0014-entry-0007-answer.mp3"
  },
  {
    "ordinal": 15,
    "entry_index": 8,
    "kind": "question",
    "display_text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "translation_text": "The egg is a symbol of which Polish religious holiday? What do we do?",
    "spoken_text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "original_text": "Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "original_reference_text": "The egg is a symbol of which Polish religious holiday? What do we do?",
    "display_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "display_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "reference_question": "Q: The egg is a symbol of which Polish religious holiday? What do we do?",
    "reference_answer": "A: It is a symbol of Easter. Polish people paint eggs then.",
    "source_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "source_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "output_file": "output-urzad-culture-pack/audio/0015-entry-0008-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0015-entry-0008-question.mp3"
  },
  {
    "ordinal": 16,
    "entry_index": 8,
    "kind": "answer",
    "display_text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "translation_text": "It is a symbol of Easter. Polish people paint eggs then.",
    "spoken_text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "original_text": "To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "original_reference_text": "It is a symbol of Easter. Polish people paint eggs then.",
    "display_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "display_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "reference_question": "Q: The egg is a symbol of which Polish religious holiday? What do we do?",
    "reference_answer": "A: It is a symbol of Easter. Polish people paint eggs then.",
    "source_question": "Q: Jajko to symbol jakiego polskiego święta religijnego? Co robimy?",
    "source_answer": "A: To symbol Wielkanocy. Polacy wtedy malują jajka.",
    "output_file": "output-urzad-culture-pack/audio/0016-entry-0008-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0016-entry-0008-answer.mp3"
  },
  {
    "ordinal": 17,
    "entry_index": 9,
    "kind": "question",
    "display_text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "translation_text": "When do Polish people visit cemeteries? Do you know which holiday it is?",
    "spoken_text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "original_text": "Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "original_reference_text": "When do Polish people visit cemeteries? Do you know which holiday it is?",
    "display_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "display_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
    "reference_question": "Q: When do Polish people visit cemeteries? Do you know which holiday it is?",
    "reference_answer": "A: On All Saints’ Day, November 1.",
    "source_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "source_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
    "output_file": "output-urzad-culture-pack/audio/0017-entry-0009-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0017-entry-0009-question.mp3"
  },
  {
    "ordinal": 18,
    "entry_index": 9,
    "kind": "answer",
    "display_text": "W Dzień Wszystkich Świętych, 1 listopada.",
    "translation_text": "On All Saints’ Day, November 1.",
    "spoken_text": "W Dzień Wszystkich Świętych, 1 listopada.",
    "text": "W Dzień Wszystkich Świętych, 1 listopada.",
    "original_text": "W Dzień Wszystkich Świętych, 1 listopada.",
    "original_reference_text": "On All Saints’ Day, November 1.",
    "display_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "display_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
    "reference_question": "Q: When do Polish people visit cemeteries? Do you know which holiday it is?",
    "reference_answer": "A: On All Saints’ Day, November 1.",
    "source_question": "Q: Kiedy Polacy odwiedzają cmentarze? Czy wiesz, jakie to święto?",
    "source_answer": "A: W Dzień Wszystkich Świętych, 1 listopada.",
    "output_file": "output-urzad-culture-pack/audio/0018-entry-0009-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0018-entry-0009-answer.mp3"
  },
  {
    "ordinal": 19,
    "entry_index": 10,
    "kind": "question",
    "display_text": "Co to są imieniny?",
    "translation_text": "What is a name day?",
    "spoken_text": "Co to są imieniny?",
    "text": "Co to są imieniny?",
    "original_text": "Co to są imieniny?",
    "original_reference_text": "What is a name day?",
    "display_question": "Q: Co to są imieniny?",
    "display_answer": "A: To dzień twojego imienia.",
    "reference_question": "Q: What is a name day?",
    "reference_answer": "A: It is the day of your given name.",
    "source_question": "Q: Co to są imieniny?",
    "source_answer": "A: To dzień twojego imienia.",
    "output_file": "output-urzad-culture-pack/audio/0019-entry-0010-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0019-entry-0010-question.mp3"
  },
  {
    "ordinal": 20,
    "entry_index": 10,
    "kind": "answer",
    "display_text": "To dzień twojego imienia.",
    "translation_text": "It is the day of your given name.",
    "spoken_text": "To dzień twojego imienia.",
    "text": "To dzień twojego imienia.",
    "original_text": "To dzień twojego imienia.",
    "original_reference_text": "It is the day of your given name.",
    "display_question": "Q: Co to są imieniny?",
    "display_answer": "A: To dzień twojego imienia.",
    "reference_question": "Q: What is a name day?",
    "reference_answer": "A: It is the day of your given name.",
    "source_question": "Q: Co to są imieniny?",
    "source_answer": "A: To dzień twojego imienia.",
    "output_file": "output-urzad-culture-pack/audio/0020-entry-0010-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0020-entry-0010-answer.mp3"
  },
  {
    "ordinal": 21,
    "entry_index": 11,
    "kind": "question",
    "display_text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "translation_text": "Do you know which song Polish people sing for birthdays?",
    "spoken_text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "original_text": "Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "original_reference_text": "Do you know which song Polish people sing for birthdays?",
    "display_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "display_answer": "A: Sto lat, sto lat.",
    "reference_question": "Q: Do you know which song Polish people sing for birthdays?",
    "reference_answer": "A: “Sto lat, sto lat.”",
    "source_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "source_answer": "A: Sto lat, sto lat.",
    "output_file": "output-urzad-culture-pack/audio/0021-entry-0011-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0021-entry-0011-question.mp3"
  },
  {
    "ordinal": 22,
    "entry_index": 11,
    "kind": "answer",
    "display_text": "Sto lat, sto lat.",
    "translation_text": "“Sto lat, sto lat.”",
    "spoken_text": "Sto lat, sto lat.",
    "text": "Sto lat, sto lat.",
    "original_text": "Sto lat, sto lat.",
    "original_reference_text": "“Sto lat, sto lat.”",
    "display_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "display_answer": "A: Sto lat, sto lat.",
    "reference_question": "Q: Do you know which song Polish people sing for birthdays?",
    "reference_answer": "A: “Sto lat, sto lat.”",
    "source_question": "Q: Czy wiesz, jaką piosenkę śpiewają Polacy na urodziny?",
    "source_answer": "A: Sto lat, sto lat.",
    "output_file": "output-urzad-culture-pack/audio/0022-entry-0011-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0022-entry-0011-answer.mp3"
  },
  {
    "ordinal": 23,
    "entry_index": 12,
    "kind": "question",
    "display_text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "translation_text": "What is your favorite Polish holiday or tradition? Why?",
    "spoken_text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "original_text": "Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "original_reference_text": "What is your favorite Polish holiday or tradition? Why?",
    "display_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "display_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "reference_question": "Q: What is your favorite Polish holiday or tradition? Why?",
    "reference_answer": "A: My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
    "source_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "source_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "output_file": "output-urzad-culture-pack/audio/0023-entry-0012-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0023-entry-0012-question.mp3"
  },
  {
    "ordinal": 24,
    "entry_index": 12,
    "kind": "answer",
    "display_text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "translation_text": "My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
    "spoken_text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "original_text": "Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "original_reference_text": "My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
    "display_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "display_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "reference_question": "Q: What is your favorite Polish holiday or tradition? Why?",
    "reference_answer": "A: My favorite Polish tradition is Christmas Eve dinner, because the whole family meets together.",
    "source_question": "Q: Jakie jest twoje ulubione polskie święto lub tradycja? Dlaczego?",
    "source_answer": "A: Moją ulubioną polską tradycją jest Wigilia, ponieważ cała rodzina spotyka się razem.",
    "output_file": "output-urzad-culture-pack/audio/0024-entry-0012-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0024-entry-0012-answer.mp3"
  },
  {
    "ordinal": 25,
    "entry_index": 13,
    "kind": "question",
    "display_text": "Czy lubi Pani Zakopane?",
    "translation_text": "Do you like Zakopane?",
    "spoken_text": "Czy lubi Pani Zakopane?",
    "text": "Czy lubi Pani Zakopane?",
    "original_text": "Czy lubi Pani Zakopane?",
    "original_reference_text": "Do you like Zakopane?",
    "display_question": "Q: Czy lubi Pani Zakopane?",
    "display_answer": "A: Tak, bardzo lubię Zakopane.",
    "reference_question": "Q: Do you like Zakopane?",
    "reference_answer": "A: Yes, I like Zakopane very much.",
    "source_question": "Q: Czy lubi Pani Zakopane?",
    "source_answer": "A: Tak, bardzo lubię Zakopane.",
    "output_file": "output-urzad-culture-pack/audio/0025-entry-0013-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0025-entry-0013-question.mp3"
  },
  {
    "ordinal": 26,
    "entry_index": 13,
    "kind": "answer",
    "display_text": "Tak, bardzo lubię Zakopane.",
    "translation_text": "Yes, I like Zakopane very much.",
    "spoken_text": "Tak, bardzo lubię Zakopane.",
    "text": "Tak, bardzo lubię Zakopane.",
    "original_text": "Tak, bardzo lubię Zakopane.",
    "original_reference_text": "Yes, I like Zakopane very much.",
    "display_question": "Q: Czy lubi Pani Zakopane?",
    "display_answer": "A: Tak, bardzo lubię Zakopane.",
    "reference_question": "Q: Do you like Zakopane?",
    "reference_answer": "A: Yes, I like Zakopane very much.",
    "source_question": "Q: Czy lubi Pani Zakopane?",
    "source_answer": "A: Tak, bardzo lubię Zakopane.",
    "output_file": "output-urzad-culture-pack/audio/0026-entry-0013-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0026-entry-0013-answer.mp3"
  },
  {
    "ordinal": 27,
    "entry_index": 14,
    "kind": "question",
    "display_text": "Jak często jeździ Pani do Zakopanego?",
    "translation_text": "How often do you go to Zakopane?",
    "spoken_text": "Jak często jeździ Pani do Zakopanego?",
    "text": "Jak często jeździ Pani do Zakopanego?",
    "original_text": "Jak często jeździ Pani do Zakopanego?",
    "original_reference_text": "How often do you go to Zakopane?",
    "display_question": "Q: Jak często jeździ Pani do Zakopanego?",
    "display_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "reference_question": "Q: How often do you go to Zakopane?",
    "reference_answer": "A: We go to Zakopane two or three times a year.",
    "source_question": "Q: Jak często jeździ Pani do Zakopanego?",
    "source_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "output_file": "output-urzad-culture-pack/audio/0027-entry-0014-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0027-entry-0014-question.mp3"
  },
  {
    "ordinal": 28,
    "entry_index": 14,
    "kind": "answer",
    "display_text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "translation_text": "We go to Zakopane two or three times a year.",
    "spoken_text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "original_text": "Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "original_reference_text": "We go to Zakopane two or three times a year.",
    "display_question": "Q: Jak często jeździ Pani do Zakopanego?",
    "display_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "reference_question": "Q: How often do you go to Zakopane?",
    "reference_answer": "A: We go to Zakopane two or three times a year.",
    "source_question": "Q: Jak często jeździ Pani do Zakopanego?",
    "source_answer": "A: Jeździmy do Zakopanego dwa albo trzy razy w roku.",
    "output_file": "output-urzad-culture-pack/audio/0028-entry-0014-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0028-entry-0014-answer.mp3"
  },
  {
    "ordinal": 29,
    "entry_index": 15,
    "kind": "question",
    "display_text": "Co Pani myśli o Krakowie i Małopolsce?",
    "translation_text": "What do you think about Kraków and Małopolska?",
    "spoken_text": "Co Pani myśli o Krakowie i Małopolsce?",
    "text": "Co Pani myśli o Krakowie i Małopolsce?",
    "original_text": "Co Pani myśli o Krakowie i Małopolsce?",
    "original_reference_text": "What do you think about Kraków and Małopolska?",
    "display_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
    "display_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "reference_question": "Q: What do you think about Kraków and Małopolska?",
    "reference_answer": "A: Kraków is very green, and Małopolska is also very green and beautiful.",
    "source_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
    "source_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "output_file": "output-urzad-culture-pack/audio/0029-entry-0015-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0029-entry-0015-question.mp3"
  },
  {
    "ordinal": 30,
    "entry_index": 15,
    "kind": "answer",
    "display_text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "translation_text": "Kraków is very green, and Małopolska is also very green and beautiful.",
    "spoken_text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "original_text": "Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "original_reference_text": "Kraków is very green, and Małopolska is also very green and beautiful.",
    "display_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
    "display_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "reference_question": "Q: What do you think about Kraków and Małopolska?",
    "reference_answer": "A: Kraków is very green, and Małopolska is also very green and beautiful.",
    "source_question": "Q: Co Pani myśli o Krakowie i Małopolsce?",
    "source_answer": "A: Kraków jest bardzo zielony, a Małopolska też jest bardzo zielona i piękna.",
    "output_file": "output-urzad-culture-pack/audio/0030-entry-0015-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0030-entry-0015-answer.mp3"
  },
  {
    "ordinal": 31,
    "entry_index": 16,
    "kind": "question",
    "display_text": "Jakie góry w Małopolsce Pani lubi?",
    "translation_text": "Which mountains in Małopolska do you like?",
    "spoken_text": "Jakie góry w Małopolsce Pani lubi?",
    "text": "Jakie góry w Małopolsce Pani lubi?",
    "original_text": "Jakie góry w Małopolsce Pani lubi?",
    "original_reference_text": "Which mountains in Małopolska do you like?",
    "display_question": "Q: Jakie góry w Małopolsce Pani lubi?",
    "display_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "reference_question": "Q: Which mountains in Małopolska do you like?",
    "reference_answer": "A: I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
    "source_question": "Q: Jakie góry w Małopolsce Pani lubi?",
    "source_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "output_file": "output-urzad-culture-pack/audio/0031-entry-0016-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0031-entry-0016-question.mp3"
  },
  {
    "ordinal": 32,
    "entry_index": 16,
    "kind": "answer",
    "display_text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "translation_text": "I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
    "spoken_text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "original_text": "Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "original_reference_text": "I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
    "display_question": "Q: Jakie góry w Małopolsce Pani lubi?",
    "display_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "reference_question": "Q: Which mountains in Małopolska do you like?",
    "reference_answer": "A: I like the mountains in Małopolska, especially the Tatra Mountains and the area around Zakopane.",
    "source_question": "Q: Jakie góry w Małopolsce Pani lubi?",
    "source_answer": "A: Lubię góry w Małopolsce, szczególnie Tatry i okolice Zakopanego.",
    "output_file": "output-urzad-culture-pack/audio/0032-entry-0016-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0032-entry-0016-answer.mp3"
  },
  {
    "ordinal": 33,
    "entry_index": 17,
    "kind": "question",
    "display_text": "Dlaczego lubi Pani Kraków albo Polskę?",
    "translation_text": "Why do you like Kraków or Poland?",
    "spoken_text": "Dlaczego lubi Pani Kraków albo Polskę?",
    "text": "Dlaczego lubi Pani Kraków albo Polskę?",
    "original_text": "Dlaczego lubi Pani Kraków albo Polskę?",
    "original_reference_text": "Why do you like Kraków or Poland?",
    "display_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
    "display_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "reference_question": "Q: Why do you like Kraków or Poland?",
    "reference_answer": "A: Kraków is very beautiful in winter as well. The snow is very beautiful.",
    "source_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
    "source_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "output_file": "output-urzad-culture-pack/audio/0033-entry-0017-question.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0033-entry-0017-question.mp3"
  },
  {
    "ordinal": 34,
    "entry_index": 17,
    "kind": "answer",
    "display_text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "translation_text": "Kraków is very beautiful in winter as well. The snow is very beautiful.",
    "spoken_text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "original_text": "Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "original_reference_text": "Kraków is very beautiful in winter as well. The snow is very beautiful.",
    "display_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
    "display_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "reference_question": "Q: Why do you like Kraków or Poland?",
    "reference_answer": "A: Kraków is very beautiful in winter as well. The snow is very beautiful.",
    "source_question": "Q: Dlaczego lubi Pani Kraków albo Polskę?",
    "source_answer": "A: Kraków jest bardzo piękny także zimą. Śnieg jest bardzo piękny.",
    "output_file": "output-urzad-culture-pack/audio/0034-entry-0017-answer.mp3",
    "output_file_from_repo_root": "output-urzad-culture-pack/audio/0034-entry-0017-answer.mp3"
  }
];
